export type AccessibilityPreferences={textScale:100|115|130;highContrast:boolean;reducedMotion:boolean;shortcuts:boolean};
export const ACCESSIBILITY_KEY='snooker-accessibility-v1';
export const defaultAccessibility:AccessibilityPreferences={textScale:100,highContrast:false,reducedMotion:false,shortcuts:false};
export function normalizeAccessibility(value:Partial<AccessibilityPreferences>|null):AccessibilityPreferences{return {textScale:[100,115,130].includes(Number(value?.textScale))?Number(value?.textScale) as AccessibilityPreferences['textScale']:100,highContrast:value?.highContrast===true,reducedMotion:value?.reducedMotion===true,shortcuts:value?.shortcuts===true}}
let previousRaw:string|null|undefined;let cached=defaultAccessibility;
export function readAccessibility(){let raw:string|null=null;try{raw=localStorage.getItem(ACCESSIBILITY_KEY)}catch{/* Defaults remain usable without storage. */}if(raw!==previousRaw){previousRaw=raw;try{cached=normalizeAccessibility(raw?JSON.parse(raw):null)}catch{cached=defaultAccessibility}}return cached}
export function subscribeAccessibility(callback:()=>void){window.addEventListener('storage',callback);window.addEventListener('snooker-accessibility',callback);return()=>{window.removeEventListener('storage',callback);window.removeEventListener('snooker-accessibility',callback)}}
export function saveAccessibility(prefs:AccessibilityPreferences){localStorage.setItem(ACCESSIBILITY_KEY,JSON.stringify(normalizeAccessibility(prefs)));window.dispatchEvent(new Event('snooker-accessibility'))}
export const keyboardRoutes:Record<string,{route:string;label:string}>={KeyD:{route:'/',label:'Dashboard'},KeyT:{route:'/training',label:'Training'},KeyE:{route:'/equipment/cues',label:'Equipment'},KeyC:{route:'/calendar',label:'Calendar'},KeyI:{route:'/inbox',label:'Inbox'},KeyM:{route:'/match/preview',label:'Match centre'},KeyS:{route:'/settings',label:'Settings & help'}};
export function shortcutRoute(event:Pick<KeyboardEvent,'altKey'|'shiftKey'|'ctrlKey'|'metaKey'|'code'|'repeat'>,editing:boolean,dialogOpen:boolean){return !editing&&!dialogOpen&&!event.repeat&&event.altKey&&event.shiftKey&&!event.ctrlKey&&!event.metaKey?keyboardRoutes[event.code]?.route:undefined}
