import {createPlayerIdentitySeed,createPlayerSliderCatalog,createPlayerBackgroundCatalog} from '../data/gameContent';
import {createNewCareerState,createStarterState,getTournamentEntryAccess,enterTournamentState} from '../hooks/useGameState';
import {describe,it,expect} from 'vitest';
import {CareerRecoveryAudit} from '../../scripts/lib/careerRecoveryAudit';
const state=(date:string,cash:number)=>({currentDate:date,season:'2026/27',player:{cash,age:16},finance:{cashFlow:50,baseCashFlow:100},lastAction:'Weekly income'});
describe('career debt recovery audit',()=>{
 it('allows an eligible unranked pathway player to enter through the real game action',()=>{let s=createNewCareerState({...createPlayerIdentitySeed,fullName:createPlayerIdentitySeed.name,handedness:createPlayerIdentitySeed.handedness as 'Right-handed'|'Left-handed',sliders:createPlayerSliderCatalog.map(s=>({...s})),backgroundId:createPlayerBackgroundCatalog[1].id,age:18,startingLevelId:'start-q-tour'});s={...s,equipment:createStarterState().equipment,competitionTables:Object.fromEntries(Object.entries(s.competitionTables).map(([key,rows])=>[key,rows.filter(r=>r.playerName!==s.player.fullName)])) as typeof s.competitionTables,rankings:s.rankings.filter(r=>r.playerName!==s.player.fullName)};const event=s.tournaments.find(t=>t.type==='Q Tour'&&getTournamentEntryAccess(s,t).allowed&&t.startDate>=s.currentDate);expect(event).toBeDefined();const entered=enterTournamentState(s,event!.id);expect(entered.tournaments.find(t=>t.id===event!.id)?.status,entered.lastAction).toBe('Entered')});
 it('tracks debt across rollovers and recovery at zero without flagging debt as failure',()=>{const a=new CareerRecoveryAudit();a.observe(state('2027-06-28',-50),'Hotel');a.observe({...state('2027-07-01',-80),season:'2027/28'},'Rollover');a.observe(state('2027-07-05',0),'Income');expect(a.summary()).toMatchObject({recovered:1,unresolved:null,lowestCash:-80});expect(a.summary().episodes[0]).toMatchObject({days:7,minimumCash:-80,recoveredOn:'2027-07-05',startingBaseIncome:100})});
 it('ignores re-observations from before an already observed recovery',()=>{const a=new CareerRecoveryAudit();a.observe(state('2027-01-01',-20),'Cost');a.observe(state('2027-01-08',30),'Income');a.observe(state('2027-01-01',-20),'Earlier checkpoint');a.observe(state('2027-01-08',30),'Advance');expect(a.summary().episodes).toHaveLength(1);expect(a.summary().episodes[0].days).toBe(7)});
 it('records same-day episodes and distinguishes a later unresolved debt',()=>{const a=new CareerRecoveryAudit();a.observe(state('2027-01-01',100),'Start');a.observe(state('2027-01-01',-10),'Purchase');a.observe(state('2027-01-01',5),'Prize');a.observe(state('2027-02-01',-20),'Hotel');a.observe(state('2027-05-02',-30),'Advance');const r=a.summary();expect(r.episodes).toHaveLength(2);expect(r.episodes[0].days).toBe(0);expect(r.unresolved).toMatchObject({days:90,minimumCash:-30});expect(r.recovered).toBe(1)});
});
