// @vitest-environment jsdom
import {beforeEach,describe,it,expect} from 'vitest';
import {createNewCareerState,createStarterState} from '../hooks/useGameState';
import {ACTIVE_SAVE_KEY,encodeCareerSave} from './saveStorage';
import {freshGuide,guideView,reconcileFirstWeekGuide} from './firstWeekGuide';
import {ACCESSIBILITY_KEY,normalizeAccessibility,readAccessibility,saveAccessibility,shortcutRoute} from './accessibility';
import {buildBugReport,recordDiagnosticAction,DIAGNOSTICS_KEY} from './bugReport';
beforeEach(()=>localStorage.clear());
describe('first-week guide',()=>{
 it('starts for new careers but leaves existing saves opt-in',()=>{expect(createNewCareerState().firstWeekGuide).toMatchObject({dismissed:false,completed:[],skipped:[]});expect(createStarterState().firstWeekGuide).toBeUndefined()});
 it('follows actual training and preserves completed milestones',()=>{let s=createNewCareerState();expect(guideView(s).current?.id).toBe('training');s.trainingAppliedWeek=1;s=reconcileFirstWeekGuide(s);expect(guideView(s).current?.id).toBe('equipment');s.trainingAppliedWeek=null;expect(guideView(s).guide?.completed).toContain('training')});
 it('keeps skipped steps separate from completed steps and persists dismissals',()=>{const s=createNewCareerState();s.firstWeekGuide={...freshGuide(s),dismissed:true,skipped:['training']};const after=JSON.parse(JSON.stringify(reconcileFirstWeekGuide(s)));expect(guideView(after).guide).toMatchObject({dismissed:true,completed:[],skipped:['training']});expect(guideView(after).current?.id).toBe('equipment')});
 it('recognises a first completed match and its preparation',()=>{const s=createNewCareerState(),m=createStarterState().matches.find(m=>m.result!=='In Progress')!;s.matches=[m];const guide=guideView(s).guide!;expect(guide.completed).toEqual(expect.arrayContaining(['entry','travel','preparation','match']));expect(guide.completed).not.toContain('equipment')});
});
describe('accessibility preferences and safe keyboard navigation',()=>{
 it('validates persisted preferences and falls back from malformed values',()=>{expect(normalizeAccessibility({textScale:999 as 100,highContrast:true})).toMatchObject({textScale:100,highContrast:true,shortcuts:false});localStorage.setItem(ACCESSIBILITY_KEY,'broken');expect(readAccessibility().textScale).toBe(100);saveAccessibility({textScale:130,highContrast:true,reducedMotion:true,shortcuts:true});expect(readAccessibility().textScale).toBe(130)});
 it('only navigates with the documented modifiers outside editing and modals',()=>{const e={altKey:true,shiftKey:true,ctrlKey:false,metaKey:false,code:'KeyT',repeat:false};expect(shortcutRoute(e,false,false)).toBe('/training');expect(shortcutRoute(e,true,false)).toBeUndefined();expect(shortcutRoute(e,false,true)).toBeUndefined();expect(shortcutRoute({...e,altKey:false},false,false)).toBeUndefined();expect(shortcutRoute({...e,repeat:true},false,false)).toBeUndefined()});
});
describe('local bug report exports',()=>{
 it('recovers the active save for crash exports without including another career’s actions',()=>{const state=createStarterState();localStorage.setItem(ACTIVE_SAVE_KEY,encodeCareerSave(state));recordDiagnosticAction(state,'/training');recordDiagnosticAction({...state,player:{...state.player,fullName:'Other Career'}},'/finance');const report=buildBugReport(null,'Crash','/');expect(report.save).toMatchObject({player:{fullName:state.player.fullName}});expect(report.recentActions).toHaveLength(1);expect(report.progress?.player).toBe(state.player.fullName)});
 it('ignores damaged action records and retains an unreadable save',()=>{localStorage.setItem(DIAGNOSTICS_KEY,'[null,{}]');localStorage.setItem(ACTIVE_SAVE_KEY,'damaged save');const report=buildBugReport(null,'Cannot load','/');expect(report.recentActions).toEqual([]);expect(report.unreadableSave).toBe('damaged save');localStorage.setItem(ACTIVE_SAVE_KEY,JSON.stringify({player:null,worldSeed:1,tournamentProgress:null}));expect(buildBugReport(null,'Invalid structure','/').progress).toBeNull()});
 it('packages the full current save and only this career’s recent actions',()=>{const s=createStarterState();recordDiagnosticAction(s,'/training');recordDiagnosticAction({...s,player:{...s.player,fullName:'Other Career'}},'/finance');const report=buildBugReport(s,'Match would not start','/settings?private=ignored');expect(report.save).toBe(s);expect(report.description).toBe('Match would not start');expect(report.game.version).toBeTruthy();expect(report.recentActions).toHaveLength(1);expect(report.recentActions[0].route).toBe('/training');expect(report.route).toBe('/settings')});
 it('bounds recent action history and omits duplicate observations',()=>{const s=createStarterState();for(let i=0;i<65;i++)recordDiagnosticAction({...s,lastAction:'Action '+i},'/calendar');recordDiagnosticAction({...s,lastAction:'Action 64'},'/calendar');const rows=JSON.parse(localStorage.getItem(DIAGNOSTICS_KEY)!);expect(rows).toHaveLength(50);expect(rows[0].action).toBe('Action 15')});
});
