import { careerLegacyOf } from '../game/careerLegacy';
import { useState } from 'react';
import { Link,useParams } from 'react-router-dom';
import { useGame } from '../context/useGame';
import { PlayerLink } from '../components/game/PlayerLink';
import { resolveProfilePlayer,playerEventHistory,playerRankingHistory,profileScouting } from '../game/playerProfile';
import { watchableMatch } from '../game/realism/scouting';
import { rivalryMeetings,rivalryStage } from '../game/careerDepth/rivalryView';
import { formatMoney } from '../utils/formatters';
export function OpponentProfilePage(){
 const {id=''}=useParams();const {gameState,actOnRealism}=useGame();const [limit,setLimit]=useState(15);
 const player=resolveProfilePlayer(gameState,id);const name=player?.playerName??id;const human=name===gameState.player.fullName;const rank=gameState.competitionTables.world.find(p=>p.playerName===name)?.ranking;
 const legacy=human?careerLegacyOf(gameState):undefined;
 const history=playerEventHistory(gameState,name);const rankings=playerRankingHistory(gameState,name);const scouting=profileScouting(gameState,name);
 const relation=player?gameState.careerDepth?.relationships[player.id]:undefined;const watch=player?watchableMatch(gameState,player.id):null;
 const recent=history.flatMap(e=>[...e.matches].reverse()).slice(0,10);
 return <div className="space-y-4 pb-6"><header className="card p-5"><div className="flex flex-wrap justify-between gap-3"><div><p className="text-xs text-green-400">Player profile</p><h1 className="mt-1 text-2xl font-bold text-white">{name}</h1><p className="mt-1 text-sm text-gray-400">{player?player.nation+' · Age '+player.age+(rank&&!player.retired?' · World #'+rank:'')+' · '+(player.retired?'Retired':player.tourSurvivalStatus):'Only surviving public results are available for this player.'}</p></div><Link className="btn-secondary" to="/rankings">Rankings</Link></div></header>
 <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[['Career matches',legacy?.matchesPlayed??player?.totalMatches],['Wins / losses',legacy?legacy.wins+' / '+legacy.losses:player?player.wins+' / '+player.losses:undefined],['Competitive titles',legacy?.trophies.length??player?.titles],['Career earnings',legacy?formatMoney(legacy.prizeMoney):player?formatMoney(player.totalPrizeMoney):undefined]].map(([label,value])=><div key={label} className="card p-4"><p className="text-xs text-gray-400">{label}</p><p className="mt-2 text-xl font-bold text-white">{value??'Not recorded'}</p></div>)}</div>
 <div className="grid gap-4 lg:grid-cols-2"><section className="card p-4"><h2 className="font-semibold text-white">Scouting report</h2>{human?<Link className="text-sm text-green-400" to="/player/attributes">View your own attributes</Link>:<><p className="mt-2 text-sm text-white">Estimated ability: <strong>{scouting.ability}</strong></p><p className="mt-2 text-xs text-gray-400">{scouting.samples} observations · {scouting.confidence}% scouting confidence. Potential and exact attributes remain private.</p><p className="mt-2 text-xs text-gray-300">{scouting.note}</p><ul className="mt-2 space-y-1 text-xs text-gray-400">{scouting.evidence.map(e=><li key={e}>{e}</li>)}</ul>{player&&<button className="btn-secondary mt-3 text-xs" disabled={!watch||player.retired} onClick={()=>actOnRealism({type:'scout',opponentId:player.id})}>{watch?'Scout recorded match · one evening':'No unreviewed match available'}</button>}<p role="status" className="mt-2 text-xs text-amber-300">{gameState.lastAction}</p></>}</section>
 <section className="card p-4"><h2 className="font-semibold text-white">Your head-to-head</h2>{relation?<><p className="mt-2 text-xl text-white">{relation.wins}–{relation.losses}{relation.draws?'–'+relation.draws:''}</p><p className="mt-1 text-xs text-gray-400">Wins–losses{relation.draws?'–draws':''} · {rivalryStage(relation)} · {relation.deciders} deciders</p><div className="mt-3 max-h-48 space-y-2 overflow-y-auto">{rivalryMeetings(gameState,relation).map(m=><p key={m.id} className="text-xs text-gray-300">{m.date} · {m.event} · {m.result} {m.score}</p>)}</div></>:<p className="mt-3 text-sm text-gray-400">{human?'This is your own profile.':'No recorded meetings with you yet.'}</p>}</section></div>
 <section className="card p-4"><h2 className="font-semibold text-white">Current form</h2><div className="mt-3 flex flex-wrap gap-2">{recent.map(m=><span key={m.id} title={m.result+' '+m.score+' vs '+m.opponent} className={'rounded px-2 py-1 text-xs '+(m.result==='Won'?'bg-green-500/15 text-green-300':'bg-surface-light text-gray-300')}>{m.result} {m.score}</span>)}</div>{!recent.length&&<p className="mt-2 text-sm text-gray-400">No published recent match records.</p>}</section>
 <section className="card p-4"><h2 className="font-semibold text-white">Titles and achievements</h2><p className="mt-1 text-xs text-gray-400">{player?.majorTitles??'Unknown'} major titles · Listed events below have surviving final results. Older aggregate totals may include events no longer retained.</p><div className="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{history.filter(e=>e.result==='Winner').map(e=><div key={e.key} className="rounded border border-amber-400/20 p-3"><p className="text-sm text-white">{e.name}</p><p className="mt-1 text-xs text-amber-300">{e.season} · {e.category}</p></div>)}</div></section>
 <section className="card p-4"><h2 className="font-semibold text-white">Ranking history</h2><div className="mt-3 max-h-64 overflow-auto"><table className="w-full text-left text-xs"><thead><tr className="text-gray-400"><th className="p-2">Season / date</th><th>World rank</th><th>One-year rank</th></tr></thead><tbody>{[...rankings].reverse().map((r,i)=><tr key={r.label+':'+i} className="border-t border-border text-gray-300"><td className="p-2">{r.label}</td><td>{r.world?'#'+r.world:'—'}</td><td>{r.oneYear?'#'+r.oneYear:'—'}</td></tr>)}</tbody></table>{!rankings.length&&<p className="text-xs text-gray-400">No historical rankings recorded.</p>}</div></section>
 <section className="card p-4"><h2 className="font-semibold text-white">Season records · every circuit</h2><div className="mt-3 max-h-72 overflow-auto"><table className="w-full whitespace-nowrap text-left text-xs"><thead><tr className="text-gray-400">{['Season','W–L','Titles','Prize','World','Youth','Amateur','Q Tour','Q School','Seniors'].map(t=><th className="p-2" key={t}>{t}</th>)}</tr></thead><tbody>{player?.seasons.map((season,i)=><tr key={season.season+':'+i} className="border-t border-border text-gray-300"><td className="p-2">{season.season}</td><td>{season.wins}–{season.losses}</td><td>{season.titles}</td><td>{formatMoney(season.prizeMoney)}</td>{[season.worldRank,season.youthRank,season.amateurRank,season.qTourRank,season.qSchoolRank,season.seniorRank].map((rank,j)=><td className="p-2" key={j}>{rank?'#'+rank:'—'}</td>)}</tr>)}</tbody></table></div></section>
 <section className="card p-4"><h2 className="font-semibold text-white">Career results</h2><p className="mt-1 text-xs text-gray-400">Published results only. Open an event for opponents and scores.</p><div className="mt-3 space-y-2">{history.slice(0,limit).map(e=><details key={e.key} className="rounded border border-border p-3"><summary className="cursor-pointer text-sm text-white">{e.date} · {e.name} · {e.result}</summary><ul className="mt-3 space-y-2 text-xs text-gray-300">{!e.matches.length&&<li>Final placing retained; individual scores are no longer stored.</li>}{e.matches.map(m=><li key={m.id}>{m.round} · <PlayerLink name={m.opponent}/> · {m.result} {m.score}</li>)}</ul></details>)}</div>{history.length>limit&&<button className="btn-secondary mt-3 text-xs" onClick={()=>setLimit(v=>v+15)}>Show more results</button>}{!history.length&&<p className="mt-2 text-xs text-gray-400">No event details survive in this save.</p>}</section>
 </div>;
}
