import {useState,useSyncExternalStore} from 'react';
import {Link,useLocation} from 'react-router-dom';
import {useGame} from '../context/useGame';
import {defaultAccessibility,readAccessibility,saveAccessibility,subscribeAccessibility,keyboardRoutes,type AccessibilityPreferences} from '../game/accessibility';
import {downloadBugReport,gameBuild} from '../game/bugReport';
export function SettingsPage(){
 const {gameState,careerSessionMode,updateFirstWeekGuide}=useGame();const location=useLocation();const prefs=useSyncExternalStore(subscribeAccessibility,readAccessibility,()=>defaultAccessibility);const [message,setMessage]=useState('');const [description,setDescription]=useState('');
 function update(change:Partial<AccessibilityPreferences>){try{saveAccessibility({...prefs,...change});setMessage('Preferences saved on this browser.')}catch{setMessage('Could not save preferences. Check browser storage permissions.')}}
 return <div className="space-y-4 pb-6"><header className="card p-5"><h1 className="text-2xl font-bold text-white">Settings & help</h1><p className="mt-2 text-sm text-gray-400">Readability, keyboard controls, first-week guidance and bug reports.</p></header>
 <section className="card p-4" aria-label="Accessibility"><h2 className="font-semibold text-white">Accessibility & readability</h2><label className="mt-3 flex flex-wrap items-center gap-3 text-sm text-gray-200">Text size<select aria-label="Text size" className="rounded border border-border bg-surface p-2" value={prefs.textScale} onChange={e=>update({textScale:Number(e.target.value) as AccessibilityPreferences['textScale']})}><option value={100}>Standard · 100%</option><option value={115}>Larger · 115%</option><option value={130}>Largest · 130%</option></select></label><p className="mt-2 text-xs text-gray-400">Larger text may require scrolling. Tables retain their own horizontal scroll.</p>
 <div className="mt-4 space-y-3">{([['highContrast','Higher text contrast'],['reducedMotion','Reduce interface motion'],['shortcuts','Enable keyboard navigation shortcuts']] as const).map(([key,label])=><label key={key} className="flex items-center gap-3 text-sm text-gray-200"><input type="checkbox" checked={prefs[key]} onChange={e=>update({[key]:e.target.checked})}/>{label}</label>)}</div><p className="mt-3 text-xs text-gray-400">Results use W (win), L (loss) and D (draw), alongside colours. Your operating system’s reduced-motion preference is also respected.</p><button type="button" className="btn-secondary mt-3 text-xs" onClick={()=>update(defaultAccessibility)}>Reset accessibility settings</button></section>
 <section className="card p-4"><h2 className="font-semibold text-white">Keyboard controls</h2><p className="mt-2 text-sm text-gray-300">Tab / Shift+Tab moves focus. Enter activates links and buttons; Space toggles checkboxes and presses focused buttons. Arrow keys change select options. Escape closes supported menus and dialogs.</p><ul className="mt-3 grid gap-2 text-xs text-gray-300 sm:grid-cols-2">{Object.entries(keyboardRoutes).map(([key,value])=><li key={key}><kbd className="rounded border border-border px-2 py-1">Alt + Shift + {key.slice(3)}</kbd> · {value.label}</li>)}</ul><p className="mt-3 text-xs text-gray-400">Shortcuts are optional and do not run while typing, choosing a select option or using a modal dialog. They navigate only; they never advance time or play a shot.</p></section>
 <section className="card p-4"><h2 className="font-semibold text-white">First-week guide</h2><p className="mt-2 text-sm text-gray-400">Follow training, equipment, entry, travel, preparation and your first match. Dismiss individual explanations or the whole guide at any time.</p>{careerSessionMode==='active'?<button type="button" className="btn-primary mt-3 text-xs" onClick={()=>updateFirstWeekGuide('resume')}>Show first-week guide</button>:<p className="mt-2 text-sm text-gray-300">The guide starts automatically with a new career.</p>}</section>
 <section className="card p-4" aria-label="Bug report"><h2 className="font-semibold text-white">Export a bug report</h2><p className="mt-2 text-sm text-gray-300">Downloads your complete save, game build, recent actions and captured interface errors. The file includes your player name and career data. Nothing is uploaded automatically.</p><label className="mt-3 block text-sm text-gray-200">What went wrong?<textarea className="mt-2 block min-h-28 w-full rounded border border-border bg-surface p-3" value={description} maxLength={8000} onChange={e=>setDescription(e.target.value)} placeholder="What you did, what you expected, and what happened instead."/></label><button type="button" className="btn-primary mt-3 text-xs" onClick={()=>{try{downloadBugReport(careerSessionMode==='active'?gameState:null,description,location.pathname);setMessage('Bug report downloaded. Attach it when reporting the problem.')}catch{setMessage('Could not export the report. Try exporting your career from Save Manager.')}}}>Download bug report</button><p className="mt-3 break-words text-xs text-gray-400">Version {gameBuild.version} · Build {gameBuild.revision}</p></section>
 <p role="status" className="text-sm text-green-300">{message}</p><Link className="inline-block text-sm text-green-300 underline" to={careerSessionMode==='active'?'/saves':'/'}>{careerSessionMode==='active'?'Open Save Manager':'Back to careers'}</Link></div>;
}
