import { getMissingTournamentEquipment } from '../../hooks/useGameState';
import { Link } from 'react-router-dom';
import { useGame } from '../../context/useGame';
import { guideSteps,guideView } from '../../game/firstWeekGuide';
export function FirstWeekGuide({expanded=false}:{expanded?:boolean}){
 const {gameState,updateFirstWeekGuide}=useGame();const {guide,current,finished}=guideView(gameState);const missing=getMissingTournamentEquipment(gameState.equipment);
 if(!guide||guide.dismissed&&!expanded)return null;
 return <section aria-label="First week guide" className="mb-3 rounded-lg border border-green-500/30 bg-surface p-3 text-sm"><div className="flex flex-wrap items-center justify-between gap-2"><h2 className="font-semibold text-white">Your first week · {guide.completed.length} of {guideSteps.length} completed</h2><button type="button" className="text-xs text-gray-300 underline" onClick={()=>updateFirstWeekGuide('dismiss')}>Dismiss guide</button></div>
 {finished?<p className="mt-2 text-green-300">{guide.skipped.length?'Guide finished — '+guide.skipped.length+' steps skipped.':'First match complete — you are ready to manage your career.'} You can revisit this guide in Settings & help.</p>:current&&<><h3 className="mt-2 font-semibold text-green-300">{current.title}</h3><p className="mt-1 text-xs leading-relaxed text-gray-300">{current.explanation}</p>{current.id==='equipment'&&<p className="mt-2 text-xs text-amber-300">{missing.length?'Still needed: '+missing.join(', '):'Your equipment meets the entry requirements.'}</p>}<div className="mt-3 flex flex-wrap items-center gap-3"><Link className="btn-primary text-xs" to={current.id==='equipment'&&!missing.includes('cue')&&missing.length?'/equipment/chalk-tips':current.route}>{current.action}</Link>{current.id==='equipment'&&<button type="button" disabled={missing.length>0} className="btn-secondary text-xs disabled:opacity-50" onClick={()=>updateFirstWeekGuide('equipment')}>Equipment checked</button>}<button type="button" className="text-xs text-gray-400 underline" onClick={()=>updateFirstWeekGuide('skip',current.id)}>Skip this explanation</button></div></>}
 <details className="mt-2 text-xs"><summary className="cursor-pointer text-gray-400">All steps · saved with this career</summary><ol className="mt-2 space-y-1">{guideSteps.map(step=><li key={step.id}><Link className="text-gray-200 underline" to={step.route}>{step.title}</Link> · {guide.completed.includes(step.id)?'✓ Completed':guide.skipped.includes(step.id)?'Skipped':'To do'}</li>)}</ol></details></section>;
}
