import { resolveTournamentFormat } from '../../data/tournamentFormats';
import { tournamentPrizeSchedule } from '../../data/tournamentPrizes';
import { useGame } from '../../context/useGame';
import type { Tournament } from '../../types/game';
import { tournamentRewards } from '../../game/tournamentRewards';
import { formatMoney } from '../../utils/formatters';
export function TournamentRewards({event}:{event:Pick<Tournament,'id'|'name'|'startDate'> & Partial<Tournament>}) {
 const {gameState}=useGame();const r=tournamentRewards(gameState,event); const schedule=tournamentPrizeSchedule(event); const fullEvent=gameState.tournaments.find(t=>t.id===event.id); const rounds=fullEvent?new Set(['Winner',...resolveTournamentFormat(fullEvent).roundStructure]):null;
 return <section aria-label="Results and rewards" className="min-w-0 rounded-lg border border-border bg-background/30 p-3 text-xs"><h3 className="font-semibold text-white">Results & rewards</h3><dl className="mt-2 grid gap-2 sm:grid-cols-2"><div><dt className="text-gray-500">{r.completed?'Your prize':'Winner prize'}</dt><dd className="text-green-300">{r.completed?(r.prize===undefined?'Not recorded':formatMoney(r.prize)):r.winnerPrize===undefined?'See event prize schedule':formatMoney(r.winnerPrize)}</dd></div><div><dt className="text-gray-500">Ranking credit</dt><dd className="text-white">{r.credit===undefined?r.rankingLabel:r.world?formatMoney(r.credit):r.credit+' points'}</dd></div><div><dt className="text-gray-500">Publication</dt><dd className="text-gray-300">{r.creditStatus}</dd></div><div><dt className="text-gray-500">Trophy status</dt><dd className="text-amber-300">{r.trophy}</dd></div></dl>{schedule && <details className="mt-2"><summary className="cursor-pointer text-green-400">Prize breakdown by finish</summary><dl className="mt-2 grid grid-cols-2 gap-x-3 gap-y-1">{Object.entries(schedule.awards).filter(([round,amount])=>amount>0&&(!rounds||rounds.has(round))).map(([round,amount])=><div key={round} className="flex flex-wrap justify-between gap-1"><dt className="text-gray-400">{round==='Final'?'Runner-up':round}</dt><dd className="text-white">{formatMoney(amount)}</dd></div>)}</dl><p className="mt-2 text-[10px] text-gray-500">Finishing awards are paid once. Successful qualifiers receive their main-event finish award. The game uses a published 2025/26 prize baseline; high-break and special bonuses are separate.</p></details>}<details className="mt-2"><summary className="cursor-pointer text-green-400">How rewards work</summary><p className="mt-2 text-gray-400">{r.explanation} Prize cash and ranking publication are separate. A ranking credit does not guarantee a rise when other results or expiring earnings change the table.</p></details></section>;
}
