import {test,expect} from '@playwright/test';
import {createStarterState} from '../src/hooks/useGameState';
import {partnerCandidates} from '../src/game/careerDepth/relationships';
import {ACTIVE_SAVE_KEY,encodeCareerSave} from '../src/game/saveStorage';
import {ACCESSIBILITY_KEY} from '../src/game/accessibility';
import {readCareerSave} from './read-career-save';
for(const [width,height,scale] of [[1920,1080,100],[1366,768,100],[1280,720,130],[390,844,100]])test(`development editor fits and persists at ${width}`,async({page})=>{
 const state=createStarterState();state.firstWeekGuide={version:1,dismissed:true,completed:[],skipped:[]};state.careerDepth!.project=null;
 state.attributes.technical['Long Potting']=77.11171428571429;state.attributes.technical.Consistency=80.06352380952382;
 state.lastAction='Marked inbox message as read.';const partner=partnerCandidates(state)[0];expect(partner).toBeTruthy();
 await page.setViewportSize({width,height});const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 await page.addInitScript(({key,value,accessibility,scale})=>{if(!sessionStorage.getItem('development-editor-test')){localStorage.setItem(key,value);localStorage.setItem(accessibility,JSON.stringify({textScale:scale,reducedMotion:true}));sessionStorage.setItem('development-editor-test','1')}},{key:ACTIVE_SAVE_KEY,value:encodeCareerSave(state),accessibility:ACCESSIBILITY_KEY,scale});
 const open=async()=>{await page.goto('/');await page.getByRole('button',{name:/Continue Career/}).click();await expect(page.getByRole('heading',{name:'Upcoming & Recent Results',exact:true})).toBeVisible();await page.evaluate(()=>{history.pushState({},'','/training');dispatchEvent(new PopStateEvent('popstate'))});await page.getByRole('button',{name:/Development & practice/}).click();};
 await open();const dialog=page.getByRole('dialog',{name:'Development project & practice partner',exact:true});
 const fits=async()=>{const box=(await dialog.boundingBox())!;expect(box.x).toBeGreaterThanOrEqual(0);expect(box.y).toBeGreaterThanOrEqual(0);expect(box.y+box.height).toBeLessThanOrEqual(height);expect(await dialog.evaluate(el=>el.scrollWidth<=el.clientWidth+1)).toBe(true);await expect(dialog.getByRole('button',{name:'Close editor'})).toBeInViewport();};
 await expect(dialog).not.toContainText('Marked inbox message as read.');await fits();await page.screenshot({path:`artifacts/development-editor-${width}-empty.png`});
 await dialog.getByLabel('Development project',{exact:true}).selectOption('cue-action');await expect(dialog).toContainText('Temporary effective consistency −2');
 await dialog.getByLabel('Development project',{exact:true}).selectOption('long-pot');await dialog.getByRole('button',{name:'Start project',exact:true}).click();
 await expect(dialog.getByRole('button',{name:'Start project',exact:true})).toBeDisabled();await expect(dialog.getByLabel('Development project',{exact:true})).toBeDisabled();
 await expect(dialog).toContainText('77.11 → 77.11 (0.00)');await expect(dialog).toContainText('80.06 → 80.06 (0.00)');
 expect(await dialog.innerText()).not.toMatch(/\d+\.\d{3,}/);await fits();await page.screenshot({path:`artifacts/development-editor-${width}-active.png`});
 await dialog.getByText('Match evidence',{exact:false}).filter({has:page.locator('strong')}).click();await expect(dialog).toContainText('Small sample; no reliable performance conclusion yet.');
 await dialog.getByLabel('Practice partner',{exact:true}).selectOption(partner.id);await dialog.getByLabel('Shared practice skill',{exact:true}).selectOption('Safety Play');
 await expect.poll(async()=> (await readCareerSave(page)).careerDepth?.partnerFocus).toBe('Safety Play');await fits();await page.screenshot({path:`artifacts/development-editor-${width}-partner.png`});
 await dialog.getByRole('button',{name:'Close editor'}).click();await page.reload();await open();
 await expect(dialog.getByLabel('Practice partner',{exact:true})).toHaveValue(partner.id);await expect(dialog.getByLabel('Shared practice skill',{exact:true})).toHaveValue('Safety Play');
 await dialog.getByRole('button',{name:'Cancel project',exact:true}).click();await expect(dialog.getByRole('button',{name:'Start project',exact:true})).toBeEnabled();
 const saved=await readCareerSave(page);expect(saved.careerDepth?.project).toBeNull();expect(saved.attributes.technical['Long Potting']).toBe(state.attributes.technical['Long Potting']);expect(errors).toEqual([]);
 await page.keyboard.press('Escape');await expect(dialog).not.toBeVisible();
});
