import {expect,test} from '@playwright/test';
import {playerWorldFixture} from '../test-support/playerWorldFixture';
import {ACTIVE_SAVE_KEY,encodeCareerSave} from '../src/game/saveStorage';
for(const width of [1280,390])test('player profiles and exhibition achievements at '+width,async({page})=>{
 const {state,opponent}=playerWorldFixture();opponent.seasons=[{season:'2025/26',matches:8,wins:6,losses:2,titles:0,prizeMoney:300,youthRank:2,amateurRank:12,qTourRank:11,status:'Youth'} as typeof opponent.seasons[number]];opponent.overallRating=82;opponent.developmentPotential=94;const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.setViewportSize({width,height:844});
 await page.addInitScript(({key,value})=>{if(!sessionStorage.getItem('profile-fixture')){localStorage.setItem(key,value);sessionStorage.setItem('profile-fixture','1')}},{key:ACTIVE_SAVE_KEY,value:encodeCareerSave(state)});
 const navigate=async(path:string)=>page.evaluate(path=>{history.pushState({},'',path);dispatchEvent(new PopStateEvent('popstate'))},path);
 await page.goto('/');await page.getByRole('button',{name:/Continue Career/}).click();await navigate('/rankings');const row=page.getByRole('row').filter({has:page.getByRole('link',{name:opponent.playerName,exact:true})}).first();await expect(row.getByRole('cell').nth(5)).toHaveText(String(Math.round(opponent.overallRating)));await expect(row.getByRole('cell').nth(6)).toHaveText(String(Math.round(Math.max(opponent.overallRating,opponent.developmentPotential))));await row.getByRole('link',{name:opponent.playerName,exact:true}).click();
 await expect(page.getByRole('heading',{name:opponent.playerName,exact:true})).toBeVisible();await expect(page.getByText('Not scouted',{exact:true})).toHaveCount(0);await expect(page.getByText(/Overall:.*Potential:/)).toHaveText('Overall: '+Math.round(opponent.overallRating)+' · Potential: '+Math.round(Math.max(opponent.overallRating,opponent.developmentPotential)));await expect(page.getByRole('heading',{name:'Your head-to-head'})).toBeVisible();await expect(page.getByRole('heading',{name:'Ranking history'})).toBeVisible();await expect(page.getByText(/Exhibition achievement/)).toBeVisible();
 const selector=page.getByLabel('Player history season');await expect(selector).toBeVisible();
 const records=page.getByRole('heading',{name:'Season records · every circuit'}).locator('../..');
 await expect(records).toContainText('2026/27 · Current');await expect(records).toContainText('2025/26');
 const rankingHistory=page.getByRole('heading',{name:'Ranking history',exact:true}).locator('..');await expect(rankingHistory).toContainText('#12');await expect(rankingHistory).toContainText('#11');
 await selector.selectOption('2025/26');await expect(page.locator('summary').filter({hasText:'Profile Open'})).toHaveCount(0);
 await selector.selectOption('2026/27');await page.locator('summary').filter({hasText:'Profile Open'}).click();await expect(page.getByText(/Final ·/)).toContainText('Won 3–2');await selector.selectOption('all');
 await records.screenshot({path:'artifacts/player-seasons-'+width+'.png'});
 await page.getByRole('button',{name:'Scout recorded match · one evening'}).click();await expect(page.getByText('Not scouted',{exact:true})).toHaveCount(0);await expect(page.getByText(/1 observations/)).toBeVisible();
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);await page.screenshot({path:'artifacts/player-profile-'+width+'.png'});
 await selector.selectOption('2026/27');
 const opponentLink=page.locator('details').filter({has:page.locator('summary').filter({hasText:'Profile Open'})}).getByRole('link').first();
 await opponentLink.click();await expect(page.getByLabel('Player history season')).toHaveValue('all');
 await navigate('/career/stats');await expect(page.getByRole('region',{name:'Exhibition achievements'})).toContainText('Profile Open');await expect(page.getByRole('region',{name:'Exhibition achievements'})).toContainText('£7,500');expect(errors).toEqual([]);
});
