import {expect,test,type Page} from '@playwright/test';
import {readFile} from 'node:fs/promises';
import {createNewCareerState,createStarterState} from '../src/hooks/useGameState';
import {ACTIVE_SAVE_KEY,encodeCareerSave} from '../src/game/saveStorage';
import {readCareerSave} from './read-career-save';
const navigate=(page:Page,path:string)=>page.evaluate(path=>{history.pushState({},'',path);dispatchEvent(new PopStateEvent('popstate'))},path);
async function seed(page:Page,state:ReturnType<typeof createStarterState>){await page.addInitScript(({key,value})=>{if(!sessionStorage.getItem('experience-fixture')){localStorage.setItem(key,value);sessionStorage.setItem('experience-fixture','1')}},{key:ACTIVE_SAVE_KEY,value:encodeCareerSave(state)});await page.goto('/');await page.getByRole('button',{name:/Continue Career/}).click()}
test('new career guide follows training, supports skipping and survives reload',async({page})=>{
 await seed(page,createNewCareerState());const guide=page.getByRole('region',{name:'First week guide'});await expect(guide).toContainText('Plan your training');await guide.getByRole('link',{name:'Open training',exact:true}).click();await page.getByRole('button',{name:'Apply Plan',exact:true}).click();await expect(guide).toContainText('Check your match equipment');await expect(guide).toContainText('Still needed: cue, usable chalk, fitted tip');await expect(guide.getByRole('button',{name:'Equipment checked'})).toBeDisabled();await guide.getByRole('button',{name:'Skip this explanation'}).click();await expect(guide).toContainText('Choose and enter an event');await guide.getByRole('button',{name:'Dismiss guide'}).click();await expect(guide).toHaveCount(0);await page.reload();await page.goto('/');await page.getByRole('button',{name:/Continue Career/}).click();await expect(guide).toHaveCount(0);await navigate(page,'/settings');await page.getByRole('button',{name:'Show first-week guide'}).click();await expect(guide).toContainText('Check your match equipment');expect((await readCareerSave(page)).firstWeekGuide?.completed).toContain('training');
});
for(const width of [1280,390])test('readable settings and keyboard controls at '+width,async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.setViewportSize({width,height:844});await seed(page,createStarterState());await navigate(page,'/settings');await page.getByLabel('Text size',{exact:true}).selectOption('130');await expect(page.locator('html')).toHaveAttribute('data-text-scale','130');expect(await page.getByRole('heading',{name:'Settings & help',exact:true}).evaluate(el=>parseFloat(getComputedStyle(el).fontSize))).toBeGreaterThan(24);await page.getByLabel('Higher text contrast').check();await page.getByLabel('Reduce interface motion').check();await page.getByLabel('Enable keyboard navigation shortcuts').check();
 await page.getByLabel('What went wrong?').fill('Typing a report');await page.keyboard.press('Alt+Shift+KeyT');await expect(page).toHaveURL('/settings');await page.getByRole('heading',{name:'Settings & help',exact:true}).click();await page.keyboard.press('Alt+Shift+KeyT');await expect(page).toHaveURL('/training');await page.keyboard.press('Alt+Shift+KeyS');await expect(page).toHaveURL('/settings');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);await page.screenshot({path:'artifacts/accessibility-'+width+'.png'});
 await navigate(page,'/rankings');await page.getByRole('button',{name:'World Ranking',exact:true}).click();
 for(const title of ['Next Target','Event Scenarios','Form']){const heading=page.getByLabel('Ranking insights').getByRole('heading',{name:title,exact:true});await heading.scrollIntoViewIfNeeded();const card=heading.locator('xpath=ancestor::div[contains(concat(" ", normalize-space(@class), " "), " card ")][1]');expect(await card.evaluate(el=>el.scrollHeight<=el.clientHeight+2&&el.scrollWidth<=el.clientWidth+2),title+' at 130%').toBe(true)}
 await navigate(page,'/settings');
 await page.reload();await page.goto('/');await page.getByRole('button',{name:/Continue Career/}).click();await navigate(page,'/settings');await expect(page.getByLabel('Text size',{exact:true})).toHaveValue('130');await expect(page.getByLabel('Higher text contrast')).toBeChecked();await page.getByRole('button',{name:'Reset accessibility settings'}).click();await expect(page.locator('html')).toHaveAttribute('data-text-scale','100');await navigate(page,'/rankings');await expect(page.locator('[aria-label="Win"]').first()).toHaveText('W');expect(errors).toEqual([]);
});
test('bug report download contains the active save, build and recent actions',async({page})=>{
 await seed(page,createStarterState());await navigate(page,'/training');await navigate(page,'/settings');await page.getByLabel('What went wrong?').fill('Reproduction: tournament entry was unavailable.');const downloadPromise=page.waitForEvent('download');await page.getByRole('button',{name:'Download bug report'}).click();const download=await downloadPromise;const report=JSON.parse(await readFile((await download.path())!,'utf8'));expect(report.format).toBe('snooker-bug-report');expect(report.game.revision).not.toBe('unknown');expect(report.description).toContain('tournament entry');expect(report.save.player.fullName).toBe((await readCareerSave(page)).player.fullName);expect(report.recentActions.some((a:{route:string})=>a.route==='/training')).toBe(true);expect(report.save.tournaments.length).toBeGreaterThan(0);
});

test('mobile keyboard navigation excludes the closed drawer and returns focus on Escape',async({page})=>{
 await page.setViewportSize({width:390,height:844});await seed(page,createStarterState());await navigate(page,'/settings');
 const open=page.getByRole('button',{name:'Open navigation',exact:true});await open.focus();await page.keyboard.press('Enter');await expect(page.getByRole('button',{name:'Close navigation',exact:true})).toBeFocused();await page.keyboard.press('Shift+Tab');await expect(page.locator('nav a').last()).toBeFocused();await page.keyboard.press('Escape');await expect(open).toBeFocused();await expect(page.locator('[inert]')).toHaveCount(1);
});
