import {expect,test} from '@playwright/test';
import {playerWorldFixture} from '../test-support/playerWorldFixture';
import {ACTIVE_SAVE_KEY,encodeCareerSave} from '../src/game/saveStorage';
for(const width of [1280,390])test('player profiles and exhibition achievements at '+width,async({page})=>{
 test.setTimeout(120000);
 const {state,opponent}=playerWorldFixture();
 opponent.seasons=[{season:'2025/26',matches:8,wins:6,losses:2,titles:0,prizeMoney:300,youthRank:2,amateurRank:12,qTourRank:11,status:'Youth'} as typeof opponent.seasons[number]];
 opponent.overallRating=82;opponent.developmentPotential=94;
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.setViewportSize({width,height:900});
 await page.addInitScript(({key,value})=>{if(!sessionStorage.getItem('profile-fixture')){localStorage.setItem(key,value);sessionStorage.setItem('profile-fixture','1')}},{key:ACTIVE_SAVE_KEY,value:encodeCareerSave(state)});
 const navigate=async(path:string)=>page.evaluate(path=>{history.pushState({},'',path);dispatchEvent(new PopStateEvent('popstate'))},path);
 await page.goto('/');await page.getByRole('button',{name:/Continue Career/}).click();await expect(page.getByRole('heading',{name:'Upcoming & Recent Results',exact:true})).toBeVisible();await navigate('/rankings');
 const row=page.getByRole('row').filter({has:page.getByRole('link',{name:opponent.playerName,exact:true})}).first();
 await expect(row.getByRole('cell').nth(5)).toHaveText('82');await expect(row.getByRole('cell').nth(6)).toHaveText('94');await row.getByRole('link',{name:opponent.playerName,exact:true}).click();
 await expect(page.getByRole('heading',{name:opponent.playerName,exact:true})).toBeVisible();
 const ratings=page.getByLabel('Public player ratings');await expect(ratings).toContainText('82');await expect(ratings).toContainText('94');
 await expect(page.getByRole('heading',{name:'Your head-to-head'})).toBeVisible();await expect(page.getByRole('heading',{name:'Ranking history'})).toHaveCount(0);
 await page.screenshot({path:'artifacts/profile-redesign-'+width+'.png',fullPage:true});
 const overview=page.getByRole('tab',{name:'Overview',exact:true});await overview.focus();await page.keyboard.press('End');
 await expect(page.getByRole('tab',{name:'History',exact:true})).toBeFocused();
 const records=page.getByRole('heading',{name:'Season records · every circuit'}).locator('../..');
 await expect(records).toContainText('2026/27 · Current');await expect(records).toContainText('2025/26');
 const rankingHistory=page.getByRole('heading',{name:'Ranking history',exact:true}).locator('../..');await expect(rankingHistory).toContainText('#12');await expect(rankingHistory).toContainText('#11');
 await page.getByRole('tab',{name:'Trophies',exact:true}).click();await expect(page.getByRole('heading',{name:'Other achievements'})).toBeVisible();await expect(page.getByText('2026/27 · Exhibition achievement',{exact:true})).toBeVisible();
 await page.getByRole('tab',{name:'Results',exact:true}).click();
 const selector=page.getByLabel('Player history season');await selector.selectOption('2025/26');await expect(page.locator('summary').filter({hasText:'Profile Open'})).toHaveCount(0);
 await selector.selectOption('2026/27');await page.locator('summary').filter({hasText:'Profile Open'}).click();
 const event=page.locator('details').filter({has:page.locator('summary').filter({hasText:'Profile Open'})});await expect(event).toContainText('Won 3–2');await selector.selectOption('all');
 await overview.click();await page.getByRole('button',{name:'Scout recorded match · one evening'}).click();await expect(page.getByText('1 observations',{exact:true})).toBeVisible();
 await page.getByRole('tab',{name:'Results',exact:true}).click();await selector.selectOption('2026/27');await event.locator('summary').click();await event.getByRole('link').first().click();
 await expect(overview).toHaveAttribute('aria-selected','true');await page.getByRole('tab',{name:'Results',exact:true}).click();await expect(selector).toHaveValue('recent');
 await navigate('/settings');await page.getByLabel('Text size',{exact:true}).selectOption('130');await navigate('/players/'+opponent.id);
 for(const name of ['Overview','Results','Trophies','History']){await page.getByRole('tab',{name,exact:true}).click();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);}
 await overview.click();
 await page.getByTestId('player-profile').locator('header').scrollIntoViewIfNeeded();
 const contained=await page.getByTestId('player-profile').locator('header').evaluate(el=>{const outer=el.getBoundingClientRect();return Array.from(el.querySelectorAll('a')).every(a=>{const r=a.getBoundingClientRect();return r.left>=outer.left&&r.right<=outer.right})});expect(contained).toBe(true);
 expect(await page.getByRole('tablist',{name:'Player profile sections'}).evaluate(el=>el.scrollWidth<=el.clientWidth+1)).toBe(true);
 await page.screenshot({path:'artifacts/profile-redesign-large-'+width+'.png',fullPage:true});
 await navigate('/career/stats#exhibition-achievements');await expect(page.getByRole('region',{name:'Exhibition achievements'})).toContainText('Profile Open');await expect(page.getByRole('region',{name:'Exhibition achievements'})).toContainText('£7,500');expect(errors).toEqual([]);
});
