import { expect,test } from '@playwright/test';
import { rivalriesFixture } from '../test-support/rivalriesFixture';
import {ACTIVE_SAVE_KEY,encodeCareerSave} from '../src/game/saveStorage';
for(const width of [1280,390])test('rivalries navigation and records at '+width,async({page})=>{
 const {state,rival,newcomer}=rivalriesFixture();
 const others = state.worldPlayers.filter(p=>p.id!==rival.id && p.id!==newcomer.id && p.playerName!==state.player.fullName).slice(0,40);
 for(const p of others) state.careerDepth!.relationships[p.id] = {...state.careerDepth!.relationships[newcomer.id], opponentId:p.id, name:p.playerName, meetings:[]};
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 await page.setViewportSize({width,height:844});
 await page.addInitScript(({key,value})=>localStorage.setItem(key,value),{key:ACTIVE_SAVE_KEY,value:encodeCareerSave(state)});
 await page.goto('/');await page.getByRole('button',{name:/Continue Career/}).click();
 if(width<1280) await page.getByRole('button',{name:/Open navigation/}).click();
 await page.getByRole('link',{name:'Rivalries',exact:true}).click();
 await expect(page.getByRole('heading',{name:'Rivalries',exact:true})).toBeVisible();
 await page.getByRole('button',{name:`View ${rival.playerName} head-to-head`,exact:true}).click();
 const card=page.getByRole('article',{name:rival.playerName+' head-to-head'});
 await expect(card).toContainText('Established rivalry');await expect(card).toContainText('H2H 2–1');
 await expect(card).toContainText('Lost 3–4');
 await page.getByLabel('Rivalry filter').selectOption('Established rivalries');
 await expect(page.getByRole('article',{name:newcomer.playerName+' head-to-head'})).toHaveCount(0);
 await page.getByLabel('Rivalry filter').selectOption('All opponents');
 await page.getByLabel('Search opponents').fill(newcomer.playerName);
 await expect(page.getByRole('article')).toHaveCount(1);await expect(page.getByRole('article')).toContainText('First meeting');
 await page.getByLabel('Search opponents').fill('');
 await page.getByRole('button',{name:`View ${newcomer.playerName} head-to-head`,exact:true}).click();
 await expect(page.getByRole('article')).toContainText(newcomer.playerName);
 await page.getByRole('button',{name:`View ${others.at(-1)!.playerName} head-to-head`,exact:true}).click();
 await expect(page.getByRole('article')).toContainText(others.at(-1)!.playerName);
 if(width>=1280) await page.evaluate(()=>document.documentElement.style.fontSize='20.8px');
 expect(await page.locator('main').evaluate(el=>el.scrollHeight<=el.clientHeight+2)).toBe(true);
 await page.screenshot({path:`artifacts/rivals-contained-${width}.png`});
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);expect(errors).toEqual([]);
});
