import { expect,test } from '@playwright/test';
import { rivalriesFixture } from '../test-support/rivalriesFixture';
import {ACCESSIBILITY_KEY} from '../src/game/accessibility';
import {ACTIVE_SAVE_KEY,encodeCareerSave} from '../src/game/saveStorage';
for(const [width,height,scale] of [[1920,1080,100],[1366,768,100],[1280,720,130],[390,844,100]])test('rivalries navigation and records at '+width,async({page})=>{
 const {state,rival,newcomer}=rivalriesFixture();
 state.firstWeekGuide={version:1,dismissed:true,completed:[],skipped:[]};
 delete state.careerDepth!.relationships[newcomer.id].intensity;
 const others = state.worldPlayers.filter(p=>p.id!==rival.id && p.id!==newcomer.id && p.playerName!==state.player.fullName).slice(0,40);
 for(const p of others) state.careerDepth!.relationships[p.id] = {...state.careerDepth!.relationships[newcomer.id], opponentId:p.id, name:p.playerName, meetings:[]};
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 await page.setViewportSize({width,height});
 await page.addInitScript(({key,value,access,scale})=>{localStorage.setItem(key,value);localStorage.setItem(access,JSON.stringify({textScale:scale,reducedMotion:true}));},{key:ACTIVE_SAVE_KEY,value:encodeCareerSave(state),access:ACCESSIBILITY_KEY,scale});
 await page.goto('/');await page.getByRole('button',{name:/Continue Career/}).click();
 await expect(page.getByRole('heading',{name:'Upcoming & Recent Results',exact:true})).toBeVisible();
 if(width<1280) await page.getByRole('button',{name:/Open navigation/}).click();
 await page.getByRole('link',{name:'Rivalries',exact:true}).click();
 await expect(page.getByRole('heading',{name:'Rivalries',exact:true})).toBeVisible();
 await page.getByRole('button',{name:`View ${rival.playerName} head-to-head`,exact:true}).click();
 const card=page.getByRole('article',{name:rival.playerName+' head-to-head'});
 await expect(card).toContainText('Established rivalry');await expect(card).toContainText('H2H 2–1');
 await page.screenshot({path:`artifacts/rivals-overview-${width}.png`});
 await page.getByRole('tab',{name:'Meetings',exact:true}).click();
 await expect(card.locator('.rivals-meeting-result').filter({hasText:'Lost'})).toContainText('3–4');
 await page.screenshot({path:`artifacts/rivals-meetings-${width}.png`});
 await page.getByRole('tab',{name:'Meetings',exact:true}).focus();await page.keyboard.press('ArrowRight');
 await expect(page.getByRole('tab',{name:'How rivalries work',exact:true})).toHaveAttribute('aria-selected','true');
 await expect(card).toContainText('at least three meetings');
 await page.getByRole('tab',{name:'Overview',exact:true}).click();
 await page.getByLabel('Rivalry filter').selectOption('Established rivalries');
 await expect(page.getByRole('article',{name:newcomer.playerName+' head-to-head'})).toHaveCount(0);
 await page.getByLabel('Rivalry filter').selectOption('All opponents');
 await page.getByLabel('Search opponents').fill(newcomer.playerName);
 await expect(page.getByRole('article')).toHaveCount(1);await expect(page.getByRole('article')).toContainText('First meeting');
 await page.getByLabel('Search opponents').fill('');
 await page.getByRole('button',{name:`View ${newcomer.playerName} head-to-head`,exact:true}).click();
 await expect(page.getByRole('article')).toContainText(newcomer.playerName);
 await expect(page.getByRole('article')).toContainText('Unrecorded');
 await page.getByRole('button',{name:`View ${others.at(-1)!.playerName} head-to-head`,exact:true}).click();
 await expect(page.getByRole('article')).toContainText(others.at(-1)!.playerName);
 await page.getByLabel('Search opponents').fill('NoMatchingNameHere');
 await expect(page.getByRole('heading',{name:'No matching opponents'})).toBeVisible();
 await page.getByRole('button',{name:'Clear filters'}).click();
 await expect(page.getByRole('article')).toHaveCount(1);
 const box=(await page.getByTestId('rivalries-page').boundingBox())!;
 expect(box.y+box.height).toBeLessThanOrEqual(height);
 expect(await page.getByRole('article').innerText()).not.toMatch(/\d+\.\d{3,}/);
 expect(await page.locator('main').evaluate(el=>el.scrollHeight<=el.clientHeight+2)).toBe(true);
 await page.screenshot({path:`artifacts/rivals-contained-${width}.png`});
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);expect(errors).toEqual([]);
 await page.getByRole('button',{name:`View ${rival.playerName} head-to-head`,exact:true}).click();
 await page.getByRole('article').getByRole('link',{name:rival.playerName,exact:true}).click();
 await expect(page).toHaveURL(new RegExp('/players/'+encodeURIComponent(rival.id)));
});

for (const width of [1366,390]) test('empty rivalry history at '+width, async ({page})=>{
 const {state}=rivalriesFixture(); state.careerDepth!.relationships={}; state.firstWeekGuide={version:1,dismissed:true,completed:[],skipped:[]};
 await page.setViewportSize({width,height:768});
 await page.addInitScript(({key,value})=>localStorage.setItem(key,value),{key:ACTIVE_SAVE_KEY,value:encodeCareerSave(state)});
 await page.goto('/'); await page.getByRole('button',{name:/Continue Career/}).click();
 await expect(page.getByRole('heading',{name:'Upcoming & Recent Results',exact:true})).toBeVisible();
 await page.evaluate(()=>{history.pushState({},'', '/career/rivalries');dispatchEvent(new PopStateEvent('popstate'))});
 await expect(page.getByRole('heading',{name:'Every rivalry starts with a match'})).toBeVisible();
 expect(await page.locator('main').evaluate(el=>el.scrollHeight<=el.clientHeight+2)).toBe(true);
 await page.screenshot({path:`artifacts/rivals-empty-${width}.png`});
 await page.getByRole('link',{name:'Go to Tournament Hub'}).click();await expect(page).toHaveURL(/tournaments\/hub/);
});
