import {expect,test} from '@playwright/test';
import {createStarterState} from '../src/hooks/useGameState';
import {ACTIVE_SAVE_KEY,ACTIVE_SAVE_SLOT_KEY,SAVE_SLOT_PREFIX,SAVE_SLOT_INDEX_KEY,encodeCareerSave} from '../src/game/saveStorage';
import {ACCESSIBILITY_KEY} from '../src/game/accessibility';
import {readCareerSave,readStoredCareerValue} from './read-career-save';
for(const [width,height,scale] of [[1920,1080,100],[1366,768,100],[1280,720,130],[390,844,100]])test('save library identifies, renames and switches careers at '+width,async({page})=>{
 const state=createStarterState();state.firstWeekGuide={version:1,dismissed:true,completed:[],skipped:[]};state.player.cash=8000;
 const other=structuredClone(state);other.player.cash=23000;other.currentDate='2026-08-20';
 const slot=(id:string,name:string,s:typeof state)=>({id,name,playerName:s.player.fullName,season:s.season,date:s.currentDate,updatedAt:'2026-09-16T02:00:00.000Z'});
 const entries=[[ACTIVE_SAVE_KEY,encodeCareerSave(state)],[ACTIVE_SAVE_SLOT_KEY,'library-current'],[SAVE_SLOT_PREFIX+'library-current',encodeCareerSave(state)],[SAVE_SLOT_PREFIX+'library-other',encodeCareerSave(other)],[SAVE_SLOT_INDEX_KEY,JSON.stringify([slot('library-current','First career',state),slot('library-other','Second career',other)])],[ACCESSIBILITY_KEY,JSON.stringify({textScale:scale,reducedMotion:true})]];
 await page.setViewportSize({width,height});const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 await page.addInitScript(entries=>{if(!sessionStorage.getItem('library-fixture')){for(const [key,value] of entries)localStorage.setItem(key,value);sessionStorage.setItem('library-fixture','1')}},entries);
 const open=async()=>{await page.goto('/');await page.getByRole('button',{name:/Continue Career/}).click();await expect(page.getByRole('heading',{name:'Upcoming & Recent Results',exact:true})).toBeVisible();await page.evaluate(()=>{history.pushState({},'','/saves');dispatchEvent(new PopStateEvent('popstate'))})};
 await open();const active=page.getByRole('region',{name:'Active career',exact:true});const selected=page.getByRole('region',{name:'Selected career',exact:true});
 await expect(active).toContainText('First career');await expect(selected.getByRole('button',{name:'Already playing'})).toBeDisabled();await expect(selected.getByRole('button',{name:'Delete First career'})).toBeDisabled();
 await page.getByRole('button',{name:'Select career Second career',exact:true}).click();await expect(selected).toContainText('2026-08-20');await expect(active).toContainText('First career');expect(await readStoredCareerValue(page,ACTIVE_SAVE_SLOT_KEY)).toBe('library-current');
 await expect(page.getByRole('region',{name:'Copy current career'})).toContainText('Copying First career');
 await selected.getByRole('button',{name:'Rename',exact:true}).click();const dialog=page.getByRole('dialog',{name:'Rename Second career'});await dialog.getByLabel('Career name').fill('Second career – tour run');await dialog.getByRole('button',{name:'Save name'}).click();await expect(dialog).not.toBeVisible();await expect(selected).toContainText('Second career – tour run');expect((await readCareerSave(page)).player.cash).toBe(8000);
 await page.screenshot({path:`artifacts/save-library-${width}.png`});
 expect(await page.locator('main').evaluate(el=>el.scrollHeight<=el.clientHeight+2)).toBe(true);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);
 await selected.getByRole('button',{name:'Open career',exact:true}).click();await expect(active).toContainText('Second career – tour run');expect((await readCareerSave(page)).player.cash).toBe(23000);
 await page.getByLabel('Save slot name').fill('Checkpoint copy');await page.getByRole('button',{name:'Create Copy',exact:true}).click();await expect(active).toContainText('Checkpoint copy');const copyId=await readStoredCareerValue(page,ACTIVE_SAVE_SLOT_KEY);expect(copyId).not.toBe('library-other');expect((await readCareerSave(page)).player.cash).toBe(23000);
 await page.getByRole('tab',{name:'Automatic backups',exact:true}).click();await expect(page.getByLabel('Recovery career')).toHaveValue(copyId!);await page.screenshot({path:`artifacts/save-backups-${width}.png`});
 await page.getByRole('tab',{name:'Import & export',exact:true}).click();await expect(page.locator('.save-transfer-source')).toContainText('Checkpoint copy');await page.screenshot({path:`artifacts/save-transfer-${width}.png`});
 await page.getByLabel('Import career file').setInputFiles({name:'invalid.json',mimeType:'application/json',buffer:Buffer.from('{}')});await expect(page.getByRole('status').filter({hasText:'not a valid'})).toBeVisible();expect(await readStoredCareerValue(page,ACTIVE_SAVE_SLOT_KEY)).toBe(copyId);
 await page.reload();await open();await expect(active).toContainText('Checkpoint copy');await expect(page.getByRole('button',{name:'Select career Second career – tour run',exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Select career First career',exact:true}).click();page.once('dialog',dialog=>dialog.dismiss());await selected.getByRole('button',{name:'Delete First career'}).click();await expect(page.getByRole('button',{name:'Select career First career',exact:true})).toBeVisible();
 expect(errors).toEqual([]);
});
