import { reconcileStaff } from '../src/game/seasonLife/staff';
import { expect, test, type Page } from '@playwright/test';
import { createStarterState, createTeamLiveMatch, type GameState } from '../src/hooks/useGameState';
import { initializeSeasonLife } from '../src/game/seasonLife';
import { member } from '../src/game/seasonLife/teams';
import { lifeOf, putLife } from '../src/game/seasonLife/shared';
import { recordForm } from '../src/game/seasonLife/form';
import { offerInterview } from '../src/game/seasonLife/media';
import { depthOf, plusDays } from '../src/game/careerDepth/shared';
import { ACTIVE_SAVE_KEY, encodeCareerSave } from '../src/game/saveStorage';
import type { TeamEvent } from '../src/game/seasonLife/types';
import { readCareerSave } from './read-career-save';
function fixture(){let s=createStarterState();s.careerDepth={...depthOf(s),seasonLife:undefined};s=initializeSeasonLife(s);s.seasonReview=null;const pool=s.worldPlayers.filter(p=>p.playerName!==s.player.fullName).slice(0,7);pool.forEach(p=>{p.retired=false;p.injuryWeeks=0;});const players=[member(s,s.player.id),...pool.map(p=>member(s,p.id))];const e:TeamEvent={id:'e2e-pairs',name:'Nations Pairs Invitational',kind:'nations',season:s.season,cutoff:s.currentDate,start:s.currentDate,end:plusDays(s.currentDate,1),deadline:s.currentDate,status:'accepted',accepted:s.currentDate,teams:Array.from({length:4},(_,i)=>({name:'Pair '+(i+1),members:[players[2*i],players[2*i+1]]})),partnerOptions:[players[1]],ties:[{home:0,away:1,results:[]},{home:2,away:3,results:[]}],fee:0,travel:100,support:100,winnerShare:1000,runnerUpShare:400};s=putLife(s,{...lifeOf(s),teams:[e]});return {s,e};}
const route=(p:Page,url:string)=>p.evaluate(url=>{history.pushState({},'',url);dispatchEvent(new PopStateEvent('popstate'));},url);
async function open(p:Page,s:GameState,url:string){await p.addInitScript(({key,value})=>{if(!sessionStorage.getItem('life-fixture')){localStorage.setItem(key,value);sessionStorage.setItem('life-fixture','yes');}},{key:ACTIVE_SAVE_KEY,value:encodeCareerSave(s)});await p.goto('/');await p.getByRole('button',{name:/Continue Career/}).click();await expect(p.locator('#main-content')).toBeVisible();await route(p,url);}
test('team singles opens in Match Centre, simulates teammate and preserves singles records',async({page})=>{const {s}=fixture();const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await open(page,s,'/career/teams');const before=await readCareerSave(page);await page.getByRole('button',{name:'Play your singles',exact:true}).click();await expect(page.getByTestId('live-match-score-centre')).toBeVisible();await page.getByRole('button',{name:/Sim Match/}).click();await expect(page.getByRole('heading',{name:'Club & national pairs'})).toBeVisible();const after=await readCareerSave(page);expect(after.matches).toEqual(before.matches);expect(after.careerDepth?.seasonLife?.teams[0].ties[0].results).toHaveLength(2);await page.getByText(/Semi-final · Pair 1/).click();await expect(page.getByText(/Teammate singles · simulated/).first()).toBeVisible();expect(errors).toEqual([]);});
test('doubles reload retains identities and exposes keyboard-accessible controls at large text',async({page})=>{const {s,e}=fixture();s.liveMatch=createTeamLiveMatch(s,e,0,2);await open(page,s,'/match/live');await page.setViewportSize({width:1024,height:768});await page.evaluate(()=>document.documentElement.style.fontSize='20px');await expect(page.getByText(/Doubles: fixed order/).first()).toBeVisible();await page.getByRole('button',{name:/Sim Frame/}).click();await expect.poll(async()=> (await readCareerSave(page)).liveMatch?.currentFrame).toBe(2);const before=await readCareerSave(page);expect(before.liveMatch?.teamContext?.members).toHaveLength(4);await page.locator('summary').filter({hasText:'fixed order'}).scrollIntoViewIfNeeded();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2)).toBe(true);await page.screenshot({path:'artifacts/season-life-doubles-large-text.png',fullPage:true});await page.getByRole('button',{name:'Return to team event',exact:true}).click();await page.getByRole('link',{name:'Resume match',exact:true}).click();await expect(page.getByTestId('live-match-score-centre')).toBeVisible();await page.reload();await page.getByRole('button',{name:/Continue Career/}).click();await expect(page.locator('#main-content')).toBeVisible();await route(page,'/match/live');await expect(page.getByTestId('live-match-score-centre')).toBeVisible();const after=await readCareerSave(page);expect(after.liveMatch?.teamContext).toEqual(before.liveMatch?.teamContext);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2)).toBe(true);await page.keyboard.press('Tab');expect(await page.evaluate(()=>document.activeElement?.tagName)).not.toBe('BODY');});
test('form evidence and recovery use the existing dialog and persist',async({page})=>{let {s}=fixture();for(let i=0;i<6;i++)s=recordForm(s,{...s.matches[0],id:'pattern-'+i,formEvidence:{openings:10,openingsMade:i<3?9:1,strongLeads:0,leadsLost:0}});await open(page,s,'/training');await page.getByRole('button',{name:/Form assessment/}).click();const dialog=page.getByRole('dialog',{name:'Form evidence and recovery'});await expect(dialog).toContainText('Modelled long openings');await dialog.getByRole('button',{name:'Tactical protection',exact:true}).click();await expect.poll(async()=> (await readCareerSave(page)).careerDepth?.seasonLife?.form?.route).toBe('protect');await dialog.getByRole('button',{name:'Close editor',exact:true}).click();});
test('optional interview uses ordinary inbox presentation and remembers one response',async({page})=>{let {s}=fixture();s=offerInterview(s,{...s.matches[0],id:'major-final',round:'Final',tournamentClass:'Major',season:s.season});await open(page,s,'/inbox');await expect(page.getByRole('button',{name:'Praise the opponent',exact:true})).toBeVisible();await page.getByRole('button',{name:'Praise the opponent',exact:true}).click();await expect(page.getByTestId('inbox-message-body').getByText(/Respectful words acknowledged. Rivalry intensity softened slightly./)).toBeVisible();expect((await readCareerSave(page)).careerDepth?.seasonLife?.interviews[0].response).toBe('praise');});

test('staff notice shows binding terms and an extension needs an explicit choice',async({page})=>{let {s}=fixture();s.coachContracts=[{coachId:s.coaches[0].id,slot:'Lead Coach',startedWeek:s.week,contractWeeks:4,weeksRemaining:4,contractLabel:'4 weeks',weeklyCost:100,totalCost:400}];s.careerDepth!.seasonLife!.staff={};s.player.cash=20000;s=reconcileStaff(s);await open(page,s,'/staff/coaches');await page.getByRole('button',{name:/Staff ambitions, renewals & junior development/}).click();const dialog=page.getByRole('dialog',{name:'Staff commitments and movement'});await expect(dialog).toContainText('13 weeks × £100 = £1300');await dialog.getByRole('button',{name:'Sign extension',exact:true}).click();await expect.poll(async()=> (await readCareerSave(page)).coachContracts[0].weeksRemaining).toBe(17);await expect(dialog.getByRole('button',{name:'Sign extension',exact:true})).toBeDisabled();});
