import { expect, test } from '@playwright/test';
import { createStarterState } from '../src/hooks/useGameState';
import { ACTIVE_SAVE_KEY, encodeCareerSave } from '../src/game/saveStorage';
import { readCareerSave } from './read-career-save';
import { sponsorVolatility } from '../src/game/sponsorVolatility';
for(const viewport of [{width:1280,height:720},{width:390,height:844}])test('seasonal sponsor offers at '+viewport.width+'px',async({page})=>{
  const fixture=createStarterState();fixture.player.reputation=100;fixture.sponsors=fixture.sponsors.slice(0,1);const existing=fixture.sponsors[0];const offer=fixture.sponsorOffers.find(o=>o.seasonal)!;
  offer.volatility='volatile';
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.setViewportSize(viewport);
  await page.addInitScript(({key,value})=>{if(!sessionStorage.getItem('seasonal-sponsors')){localStorage.setItem(key,value);sessionStorage.setItem('seasonal-sponsors','1')}},{key:ACTIVE_SAVE_KEY,value:encodeCareerSave(fixture)});
  await page.goto('/');await page.getByRole('button',{name:/Continue Career/}).click();await expect(page.getByRole('heading',{name:'Upcoming & Recent Results',exact:true})).toBeVisible();
  const navigate=async(path:string)=>page.evaluate(path=>{history.pushState({},'',path);dispatchEvent(new PopStateEvent('popstate'))},path);
  await navigate('/sponsorship');await expect(page.getByText(/2026\/27 ·/).first()).toBeVisible();await expect(page.getByRole('button',{name:offer.name,exact:true})).toBeVisible();
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);
  await page.getByRole('group',{name:'Sponsor slots'}).getByRole('button',{name:new RegExp(existing.name)}).click();
  await expect(page.getByRole('dialog').getByText('Walk-away point: below 25/100 after 6 recovery matches.')).toBeVisible();
  await expect(page.getByRole('dialog').getByText(`${sponsorVolatility(existing).label} volatility · ${Math.round(sponsorVolatility(existing).multiplier*100)}% result reaction`,{exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Close editor',exact:true}).click();
  await navigate('/sponsorship/contract?offer='+offer.id);
  await page.getByRole('tab',{name:'Performance',exact:true}).click();
  await expect(page.getByText(/To sign:.*reputation/)).toBeVisible();
  await expect(page.getByText(/All sponsors: below 40\/100/)).toBeVisible();
  await expect(page.getByText(/All sponsors: below 40\/100/)).toContainText('below 25/100');
  await expect(page.getByText(/Volatile volatility · 140% result reaction/)).toBeVisible();
  await page.getByRole('tab',{name:'Negotiation',exact:true}).click();await page.getByRole('button',{name:/Increase Base Pay/}).click();await page.evaluate(()=>{Math.random=()=>0});await page.getByRole('button',{name:'Submit Negotiation',exact:true}).click();
  await expect.poll(async()=>((await readCareerSave(page)).sponsorOffers.find(o=>o.id===offer.id)?.monthlyValue??0)).toBeGreaterThan(offer.monthlyValue);
  const quote=(await readCareerSave(page)).sponsorOffers.find(o=>o.id===offer.id)!;
  await page.reload();await page.getByRole('button',{name:/Continue Career/}).click();await expect(page.getByRole('heading',{name:'Upcoming & Recent Results',exact:true})).toBeVisible();await navigate('/sponsorship/contract?offer='+offer.id);
  expect((await readCareerSave(page)).sponsorOffers.find(o=>o.id===offer.id)?.monthlyValue).toBe(quote.monthlyValue);
  await page.getByRole('button',{name:'Accept Contract',exact:true}).click();
  await expect.poll(async()=>(await readCareerSave(page)).sponsors.some(s=>s.id===offer.id)).toBe(true);
  const saved=await readCareerSave(page);expect(saved.sponsors.find(s=>s.id===offer.id)?.monthlyValue).toBe(quote.monthlyValue);expect(saved.sponsors.find(s=>s.id===existing.id)?.monthlyValue).toBe(existing.monthlyValue);expect(saved.sponsors.find(s=>s.id===existing.id)?.weeksRemaining).toBe(existing.weeksRemaining);
  expect(saved.sponsors.find(s=>s.id===offer.id)?.volatility).toBe('volatile');
  await navigate('/sponsorship/contract?offer=expired-company-last-season');await expect(page.getByText('Offer unavailable',{exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Accept Contract',exact:true})).toHaveCount(0);
  expect(errors).toEqual([]);
});

test('small seasonal contracts negotiate down without increasing pay or duration',async({page})=>{
  const fixture=createStarterState();fixture.player.reputation=100;const offer=fixture.sponsorOffers.find(o=>o.seasonal)!;offer.monthlyValue=125;offer.contractLength='6 months';
  await page.addInitScript(({key,value})=>localStorage.setItem(key,value),{key:ACTIVE_SAVE_KEY,value:encodeCareerSave(fixture)});
  await page.goto('/');await page.getByRole('button',{name:/Continue Career/}).click();await expect(page.getByRole('heading',{name:'Upcoming & Recent Results',exact:true})).toBeVisible();
  await page.evaluate(path=>{history.pushState({},'',path);dispatchEvent(new PopStateEvent('popstate'));Math.random=()=>0},'/sponsorship/contract?offer='+offer.id);
  await page.getByRole('tab',{name:'Negotiation',exact:true}).click();await page.getByRole('button',{name:/Reduce Obligations/}).click();await page.getByRole('button',{name:'Submit Negotiation',exact:true}).click();
  await expect.poll(async()=>(await readCareerSave(page)).sponsorOffers.find(o=>o.id===offer.id)?.monthlyValue).toBe(50);
  await page.getByRole('button',{name:/Shorten Contract Length/}).click();await page.getByRole('button',{name:'Submit Negotiation',exact:true}).click();
  await expect.poll(async()=>(await readCareerSave(page)).sponsorOffers.find(o=>o.id===offer.id)?.contractLength).toBe('3 months');
  expect((await readCareerSave(page)).sponsorOffers.find(o=>o.id===offer.id)?.monthlyValue).toBe(50);
});
