import { expect, test } from '@playwright/test';
import { createStarterState } from '../src/hooks/useGameState';
import { ACCESSIBILITY_KEY } from '../src/game/accessibility';
import { readCareerSave } from './read-career-save';
import { ACTIVE_SAVE_KEY, encodeCareerSave } from '../src/game/saveStorage';

for (const [width, height, scale] of [[1920,1080,100],[1366,768,100],[1280,720,130],[390,844,100]]) test(`training location benefits are readable before booking at ${width}`, async ({ page }) => {
  const state = createStarterState();
  state.firstWeekGuide = { version: 1, dismissed: true, completed: [], skipped: [] };
  state.lastAction = 'Marked inbox message as read.';
  await page.setViewportSize({ width, height });
  await page.addInitScript(({ key, value, scale, accessKey }) => {
    if (!sessionStorage.getItem('base-benefits')) { localStorage.setItem(key, value); localStorage.setItem(accessKey, JSON.stringify({textScale: scale, reducedMotion: true})); sessionStorage.setItem('base-benefits', '1'); }
  }, { key: ACTIVE_SAVE_KEY, value: encodeCareerSave(state), scale, accessKey: ACCESSIBILITY_KEY });
  await page.goto('/'); await page.getByRole('button', { name: /Continue Career/ }).click();
  await expect(page.getByRole('heading', { name: 'Upcoming & Recent Results', exact: true })).toBeVisible();
  await page.evaluate(() => { history.pushState({}, '', '/training'); dispatchEvent(new PopStateEvent('popstate')); });
  await page.getByRole('button', { name: 'Training base: Manage' }).click();
  const dialog = page.getByRole('dialog', { name: 'Training base and relocation' });
  const benefits = dialog.getByRole('region', { name: 'Location training benefits' });
  await expect(benefits).toContainText('Safety Play');
  await expect(benefits).toContainText('Big Match Nerve');
  await expect(dialog).not.toContainText('Marked inbox message as read.');
  await expect(dialog.getByRole('button', {name: 'Confirm base and costs'})).toBeDisabled();
  await dialog.getByLabel('Base location').selectOption('Wuhan');
  await expect(benefits).toContainText('Long Potting');
  await expect(benefits).toContainText('Break Building');
  await expect(benefits).toContainText('+6%');
  await expect(benefits.locator('.base-tradeoff')).toContainText('Safety Play');
  await dialog.getByLabel('Base location').selectOption('Sydney');
  await expect(benefits).toContainText('Shoulder Health');
  await expect(benefits).toContainText('Recovery Rate');
  await expect(benefits.locator('.base-tradeoff')).toContainText('Break Building');
  await expect(benefits.locator('.base-tradeoff')).toContainText('−4%');
  await expect(dialog.getByRole('button', { name: 'Confirm base and costs' })).toBeEnabled();
  expect(await dialog.evaluate(el => el.scrollWidth <= el.clientWidth + 1)).toBe(true);
  expect(await benefits.innerText()).not.toMatch(/\d+\.\d{3,}/);
  const box = (await dialog.boundingBox())!;
  expect(box.y).toBeGreaterThanOrEqual(0);
  expect(box.y + box.height).toBeLessThanOrEqual(height);
  await expect(dialog.getByRole('button', {name: 'Confirm base and costs'})).toBeInViewport();
  await page.screenshot({ path: `artifacts/training-base-benefits-${width}.png` });
  await dialog.getByLabel('Base location').selectOption('Britain');
  await dialog.getByRole('button', { name: /Dedicated rented table/ }).click();
  const quote = dialog.getByRole('contentinfo', {name: 'Base cost summary'});
  await expect(quote).toContainText('£180');
  await expect(quote).toContainText('£360 over four weeks');
  await dialog.getByRole('button', {name: 'Confirm base and costs'}).click();
  await expect.poll(async () => (await readCareerSave(page)).realism?.base).toBe('rented');
  expect((await readCareerSave(page)).player.cash).toBe(state.player.cash - 180);
  await expect(dialog.getByRole('button', {name: 'Confirm base and costs'})).toBeDisabled();
  await dialog.getByRole('button', { name: 'Close editor' }).click();
  await page.getByRole('button', { name: 'Training base: Manage' }).click();
  await expect(dialog.getByRole('button', {name: /Dedicated rented table/})).toHaveAttribute('aria-pressed', 'true');
  await page.keyboard.press('Escape');
  await expect(dialog).not.toBeVisible();
});
