import { FormAssessmentEditor } from './FormAssessmentEditor';
import { PlayerLink } from '../game/PlayerLink';
import { PlayerNames } from '../game/PlayerNames';
import { Link } from 'react-router-dom';
import { useGame } from '../../context/useGame';
import { CareerDisclosure } from './CareerDepthPanels';
import { staffUnavailable } from '../../game/seasonLife/staff';
const button='btn-secondary min-h-10 whitespace-normal px-3 py-2 text-xs';
export function FormRecoveryPanel({ compact = false }: { compact?: boolean }) {
 const { gameState: s } = useGame();
 const life = s.careerDepth?.seasonLife, form = life?.form;
 const evidence = life?.evidence ?? [];
 return <CareerDisclosure preview={compact ? { label: "Form assessment", detail: form ? `${form.kind === 'long-pot' ? 'Long openings' : 'Closing frames'} · ${form.progress.toFixed(0)}% recovery` : `No active concern · ${evidence.length} matches with simulation evidence`, action: "Review" } : undefined} summary={form ? `Form assessment · ${form.kind === 'long-pot' ? 'Long openings' : 'Closing frames'} · ${form.progress.toFixed(0)}% recovery` : 'Form assessment · simulation evidence'} title="Form evidence and recovery">
  <FormAssessmentEditor/>
 </CareerDisclosure>;
}
export function StaffMovementPanel({ inline = false, coachId }: { inline?: boolean; coachId?: string }){
 const {gameState:s,actOnCareer}=useGame(),l=s.careerDepth?.seasonLife;
 const content = <div className="space-y-4 text-sm">
 <header className="rounded-xl border border-green-500/25 bg-green-500/5 p-4"><h2 className="text-base font-bold text-white">Renewals & ambitions</h2><p className="mt-1 text-gray-300">Contract deadlines, promises and your junior coaches’ next steps.</p></header>
 <p>Existing contracts stay binding. Renewals require your choice; ignoring a notice spends no money. Juniors use the same unlocked staff slots as senior coaches.</p>
 {Object.entries(l?.staff??{}).filter(([id,r])=>(!coachId || id === coachId) && (r.notice||r.employer||s.coachContracts.some(c=>c.coachId===id))).map(([id,r])=><section key={id} className="rounded-xl border border-border bg-surface p-4 space-y-3"><h3 className="font-semibold">{s.coaches.find(c=>c.id===id)?.name} · {r.ambition}</h3><p><PlayerNames text={staffUnavailable(s,id)??`Current contract ends ${r.end??'when signed terms end'}.`}/></p>{id.startsWith('junior-coach-')&&<p>Coaching experience {r.experience}. Gains from completed relevant training; an employed senior mentor accelerates development.</p>}
 {r.notice&&<><p><PlayerNames text={r.notice.reason}/></p><p>Decision by {r.notice.deadline}. Default: contract expires; no automatic spending. {r.notice.destination && <>Outside interest: <PlayerLink name={s.worldPlayers.find(p=>p.id===r.notice!.destination)?.playerName ?? 'Unknown player'} id={r.notice.destination}/>.</>}</p><p>Extension: 13 weeks × £{r.notice.quotedWeekly} = £{r.notice.quotedWeekly*13}, paid weekly. Current terms are honoured.</p><div className="flex flex-wrap gap-2">{(['extend','facilities','workload','decline'] as const).map(choice=><button className={button} key={choice} disabled={Boolean(r.notice?.choice&&!(choice==='extend'&&r.notice.choice==='promise'))||s.currentDate>=r.notice!.deadline||!s.coachContracts.some(c=>c.coachId===id)} onClick={()=>actOnCareer({type:'life-staff',id,choice})}>{({extend:'Sign extension',facilities:'Promise academy in 28 days',workload:'Promise reduced strain in 28 days',decline:'Decline renewal request'})[choice]}</button>)}</div></>}
 {id.startsWith('junior-coach-')&&r.experience>=12&&!r.juniorResponsibility&&<div className="flex flex-wrap gap-2"><p>Responsibility review by {l?.stories.find(x=>x.id==='junior:'+id)?.deadline}. Default: retain supported role.</p>{(['supported','specialist'] as const).map(choice=><button key={choice} className={button} onClick={()=>actOnCareer({type:'life-junior-review',id,choice})}>{choice==='supported'?'Retain supported role':'Lead own specialism'}</button>)}</div>}
 {r.promise&&<p>Promise: {r.promise.kind} by {r.promise.due} · {r.promise.met===undefined?'Awaiting review':r.promise.met?'Fulfilled':'Missed; existing terms honoured'}. Arrange changes through Training.</p>}{r.history.slice(-3).map((h,i)=><p key={i} className="text-gray-400">{h.date} · <PlayerNames text={h.text}/></p>)}</section>)}
 <p>Replacement shortlist: {s.coaches.filter(c=>!s.coachContracts.some(x=>x.coachId===c.id)&&!staffUnavailable(s,c.id)).sort((a,b)=>a.weeklyCost-b.weeklyCost).slice(0,3).map(c=>`${c.name} (£${c.weeklyCost}/week)`).join(' · ')}. Normal eligibility and slot limits apply.</p><Link to="/training" className="text-green-400">Continue training independently</Link></div>;
 return inline ? content : <CareerDisclosure summary="Staff ambitions, renewals & junior development" title="Staff commitments and movement">{content}</CareerDisclosure>;
}
export { TeamEventsPage } from '../../routes/TeamEventsPage';
export function SeasonLifeInbox({messageId}:{messageId:string}){
 const {gameState:s,actOnCareer}=useGame(),l=s.careerDepth?.seasonLife;
 const i=l?.interviews.find(i=>i.id===messageId),story=l?.stories.find(x=>messageId===x.id||messageId.startsWith(x.id+':'));
 if(!i&&!story)return null;
 return <div className="mt-3 space-y-3 rounded border border-border p-3 text-sm">
 {i&&<><p><PlayerNames text={i.context}/></p><p>Deadline {i.deadline}. No reply means declining comment without penalty.</p>{!i.response&&s.currentDate<=i.deadline?<div className="flex flex-wrap gap-2">{(['praise','candid','challenge','private'] as const).map(response=><button className={button} key={response} onClick={()=>actOnCareer({type:'life-interview',id:i.id,response})}>{({praise:'Praise the opponent',candid:'Speak candidly',challenge:'Competitive challenge',private:'Remain private'})[response]}</button>)}</div>:<p><PlayerNames text={i.reaction}/></p>}</>}
 {story&&<><p><PlayerNames text={story.defaultText}/> {story.deadline&&`Deadline: ${story.deadline}.`}</p>{story.steps.map((x,j)=><p key={j}>{x.date} · <PlayerNames text={x.text}/></p>)}{story.kind==='form'?<FormRecoveryPanel/>:story.kind==='staff'||story.kind==='junior'?<StaffMovementPanel/>:story.kind==='team'?<Link className={button} to="/career/teams">View invitation, partnership and results</Link>:!story.resolved&&story.steps.length===1&&s.currentDate<=(story.deadline??'')?<button className={button} onClick={()=>actOnCareer({type:'life-return',id:story.id})}>Welcome their return</button>:null}</>}
 </div>;
}
export function TeamLivePanel(){const {gameState:s,actOnCareer}=useGame(),c=s.liveMatch?.teamContext;if(!c)return null;return <details className="shrink-0 rounded border border-border px-3 py-2 text-xs" open><summary className="cursor-pointer">{c.kind} · at table: <PlayerLink name={c.members[c.order[c.turn]].name} id={c.members[c.order[c.turn]].id}/> · fixed order {c.order.map((i,index)=><span key={i}>{index > 0 && ' → '}<PlayerLink name={c.members[i].name} id={c.members[i].id}/></span>)}</summary>{c.foulReplayTurn!==undefined&&<button className={button} onClick={()=>actOnCareer({type:"life-foul-replay"})}>Request offender to play again</button>}<div className="mt-2 grid grid-cols-2 gap-2 lg:grid-cols-4">{c.members.map(p=><div key={p.id}><b><PlayerLink name={p.name} id={p.id}/></b><p>Confidence {p.confidence.toFixed(2)}% · fatigue {p.fatigue.toFixed(2)}%</p><p>{p.visits} visits · {p.points} points · {p.fouls} fouls</p></div>)}</div></details>}

export function SeasonLifeHistoryPanel({ inline = false }: { inline?: boolean }){const {gameState:s}=useGame(),l=s.careerDepth?.seasonLife;const content=<div className="space-y-4 text-sm"><Link to="/career/teams" className={button}>Team trophy cabinet and doubles results</Link><p>Team trophies: {(l?.teams.filter(e=>e.champion===e.teams[0]?.name).length??0)+(l?.archivedTeams?.filter(e=>e.won).length??0)}. Stored separately from singles and major titles.</p>{l?.summaries.map((x,i)=><p key={i}>{x.season} · <PlayerNames text={x.text}/></p>)}{l?.stories.filter(x=>x.resolved).slice(0,20).map(x=><article key={x.id}><h3 className="font-semibold"><PlayerNames text={x.title}/> · {x.resolved}</h3><p><PlayerNames text={x.steps.at(-1)?.text}/></p></article>)}{Boolean(l?.archivedStories?.length)&&<details><summary>Earlier story conclusions · {l?.archivedStories?.length}</summary>{l?.archivedStories?.slice().reverse().map(x=><p key={x.id}>{x.date} · <PlayerNames text={x.title}/>: <PlayerNames text={x.text}/></p>)}</details>}{l?.interviews.filter(i=>i.response).slice(0,20).map(i=><article key={i.id}><h3 className="font-semibold">{i.title} · {i.answered}</h3><p><PlayerNames text={i.context}/></p><p>{i.response} · <PlayerNames text={i.reaction}/></p></article>)}</div>;return inline ? content : <CareerDisclosure summary="Season stories, interviews & team trophies" title="In-season career history">{content}</CareerDisclosure>;}
