const fs=require('fs'),path=require('path'),crypto=require('crypto'),cp=require('child_process');
const directory=path.resolve(process.argv[2] ?? 'artifacts/simulations/50-year-world-report');
const input=fs.readFileSync(path.join(directory,'50-year-world-report.md'),'utf8');
const escape=s=>s.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const inline=s=>escape(s).replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>').replace(/\[([^\]]+)\]\(([^)]+)\)/g,(_,label,url)=>'<a href="'+escape(path.basename(url))+'">'+label+'</a>');
let body=[], table=false, dossier=false, season='';
for(const line of input.split('\n')){
 if(line.startsWith('|')){if(/^\|[ -]+\|/.test(line))continue;const cells=line.split('|').slice(1,-1).map(s=>inline(s.trim()));if(!table){body.push('<div class="table-wrap"><table><thead><tr>'+cells.map(s=>'<th>'+s+'</th>').join('')+'</tr></thead><tbody>');table=true;}else body.push('<tr>'+cells.map(s=>'<td>'+s+'</td>').join('')+'</tr>');continue;}
 if(table){body.push('</tbody></table></div>');table=false;}
 if(!line.trim())continue;
 if(line.startsWith('### ')){if(dossier)body.push('</details>');dossier=true;season=line.slice(4);body.push('<details class="season" data-season="'+escape(season)+'"><summary>'+inline(season)+'</summary>');continue;}
 if(line.startsWith('## ')){if(dossier){body.push('</details>');dossier=false;}const heading=line.slice(3);body.push('<h2 id="'+escape(heading.toLowerCase().replaceAll(' ','-'))+'">'+inline(heading)+'</h2>');continue;}
 if(line.startsWith('# ')){body.push('<h1>'+inline(line.slice(2))+'</h1>');continue;}
 if(line.startsWith('- ')){body.push('<p class="download">'+inline(line.slice(2))+'</p>');continue;}
 body.push('<p>'+inline(line)+'</p>');
}
if(table)body.push('</tbody></table></div>');if(dossier)body.push('</details>');
const html='<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>50-year Snooker World Audit</title><style>body{margin:0;background:#f4f6f8;color:#17232d;font:15px/1.65 system-ui,sans-serif}main{max-width:1180px;margin:auto;padding:28px}h1{font-size:34px;line-height:1.2}h2{margin-top:44px;border-top:2px solid #cbd5dc;padding-top:22px;scroll-margin-top:70px}a{color:#006b54}p{max-width:1050px}nav{position:sticky;top:0;background:#122a25;color:white;padding:12px 24px;display:flex;gap:18px;flex-wrap:wrap;z-index:2}nav a{color:#a3f0ca;text-decoration:none}.table-wrap{overflow:auto;margin:18px 0;border:1px solid #d5dee4;border-radius:6px;background:white}table{border-collapse:collapse;width:100%;font-size:13px}th,td{text-align:left;vertical-align:top;padding:9px 11px;border-bottom:1px solid #e2e8ee}th{background:#edf3f0;white-space:nowrap}tr:nth-child(even){background:#f8fafb}details{background:white;border:1px solid #d5dee4;padding:14px 18px;margin:12px 0;border-radius:7px}summary{cursor:pointer;font-size:20px;font-weight:700;color:#006b54}.download{display:inline-block;margin:5px 14px 5px 0}button{padding:9px 14px;border:1px solid #98b4aa;border-radius:4px;background:#fff;color:#164936;cursor:pointer}footer{margin-top:40px;color:#546771;font-size:12px}@media(max-width:600px){main{padding:16px}nav{position:static}h1{font-size:27px}}@media print{nav,button{display:none}body{background:white}main{max-width:none;padding:0}details{break-inside:auto}.table-wrap{overflow:visible}h2{break-before:page}}</style><nav><a href="#verdict-and-findings">Findings</a><a href="#all-seasons">All seasons</a><a href="#generational-development">Development</a><a href="#every-circuit-at-rollover">Circuits</a><a href="#detailed-season-dossiers">Season dossiers</a><a href="#downloads-and-evidence">Data files</a></nav><main><button id="expand">Expand all season dossiers</button> '+body.join('\n')+'<footer>Generated from saved simulation evidence. No external fonts, scripts or services.</footer></main><script>document.getElementById("expand").addEventListener("click",function(){const open=this.textContent.startsWith("Expand");document.querySelectorAll("details.season").forEach(d=>d.open=open);this.textContent=open?"Collapse all season dossiers":"Expand all season dossiers";});window.addEventListener("beforeprint",()=>document.querySelectorAll("details").forEach(d=>d.open=true));</script></html>';
fs.writeFileSync(path.join(directory,'50-year-world-report.html'),html);
const walk=d=>fs.readdirSync(d,{withFileTypes:true}).flatMap(e=>e.isDirectory()?walk(path.join(d,e.name)):[path.join(d,e.name)]);
const sources=walk('src').sort();const hash=crypto.createHash('sha256');for(const file of sources){hash.update(file.replaceAll('\\','/'));hash.update(fs.readFileSync(file));}
const manifest={generatedAt:new Date().toISOString(),seed:20260906,gitHead:cp.execSync('git rev-parse HEAD',{encoding:'utf8'}).trim(),sourceTreeSha256:hash.digest('hex'),sourceFiles:sources.length,workingTree:'Includes uncommitted world-integrity, season-review and event-finance changes. Source hash captures final code; the 50-year run preceded only the strict missing-field guard, provisional senior preview fill and schema marker. The completed run had no missing fields.',command:process.argv[3] ?? 'npx tsx scripts/simulateFiveSeasons.ts --seasons=50 --rookie-pro-21 --seed=20260906 --skip-player-snapshots --skip-shared-audits --world-audit'};
fs.writeFileSync(path.join(directory,'run-manifest.json'),JSON.stringify(manifest,null,2));
console.log(path.join(directory,'50-year-world-report.html'));
