const fs = require('fs');
const path = require('path');
const source = process.argv[2];
if (!source) throw Error('Usage: node scripts/summarizeWorldAudit.cjs <world-audit-directory>');
const out = path.resolve(process.argv[3] ?? 'artifacts/simulations/50-year-world-report');
const managedPath=source.replace(/-world[\\/]?$/, '')+'.json';
const managed=fs.existsSync(managedPath)?JSON.parse(fs.readFileSync(managedPath,'utf8')):null;
fs.mkdirSync(out, {recursive:true});
const csvCell = v => '"'+String(v??'').replaceAll('"','""')+'"';
const writeCsv = (name, headings, rows) => fs.writeFileSync(path.join(out,name),[headings,...rows].map(row=>row.map(csvCell).join(',')).join('\n'));
const average = a => a.length ? a.reduce((n,x)=>n+x,0)/a.length : 0;
const fmt = n => Number(n).toLocaleString('en-GB',{maximumFractionDigits:1});
const pct = (a,b) => b ? (100*a/b).toFixed(1)+'%' : '—';
const majorNames = ['World Championship','UK Championship','Masters','Tour Championship','Champion of Champions'];
const seasons=[], eventCsv=[], playerCsv=[], issueCsv=[], rankingCsv=[], titleCounts=new Map(), worldCounts=new Map(), numberOnes=new Map();
let initialNames, previousRoster, expected=0, completed=0, matches=0, invalidScores=0, mismatchedRecords=0, majorCountMissing=0, breakCountMissing=0, anonymousChampions=0, anonymousTitles=0, fillerEntries=0, ageViolations=0, namedQualifications=0, missingCards=0, eventsBeyondRollover=0;
const actualTitleTotals=new Map(), actualMajorTotals=new Map(), rawIssuesByKind={};
let retiredNamedFlags=0;
for (const file of fs.readdirSync(source).filter(n=>/^\d{4}-\d{2}\.json$/.test(n)).sort()) {
 const d=JSON.parse(fs.readFileSync(path.join(source,file),'utf8'));
 for(const issue of d.issues){rawIssuesByKind[issue.kind]=(rawIssuesByKind[issue.kind]??0)+1;if(issue.kind==='retired-entry' && issue.detail.slice(issue.detail.indexOf(':')+1).split(',').some(n=>!/^Qualifier \d+$/.test(n.trim())))retiredNamedFlags++;}
 for(const row of d.rankings)rankingCsv.push([d.season,'world','Frozen closing standings',row.ranking,row.playerName,row.points]);
 for(const [circuit,rows]of Object.entries(d.closingCircuitTablesBeforeFinalAdvance))if(circuit!=='world')for(const row of rows)rankingCsv.push([d.season,circuit,'Before final calendar advance',row.ranking,row.playerName,row.points,row.eventsPlayed,row.wins,row.losses,row.titles]);
 if(!initialNames) initialNames=new Set(d.roster.filter(p=>!d.newcomers.some(n=>n.id===p.id)).map(p=>p.name));
 const roster=new Map(d.roster.map(p=>[p.name,p])), actual=new Map();
 const eventAnomalies=[], qualificationRows=[];
 const get=n=>{if(!actual.has(n))actual.set(n,{matches:0,wins:0,losses:0,draws:0,titles:0,majors:0});return actual.get(n)};
 for(const e of d.events){
  if(e.date>d.endedOn){eventsBeyondRollover++;eventAnomalies.push({kind:'event-after-rollover',detail:e.name+': official completion '+e.date+', review '+d.endedOn});}
  const names=[...new Set(e.bracket.flatMap(r=>r.matches.flatMap(m=>[m.top.name,m.bottom.name])))].filter(n=>n!=='TBD');
  const fillers=names.filter(n=>!roster.has(n) || /^Qualifier \d+$/.test(n)); fillerEntries+=fillers.length;
  if(fillers.length)eventAnomalies.push({kind:'non-persistent-entrants',detail:e.name+': '+fillers.length+' / '+names.length+' entrants, examples '+fillers.slice(0,3).join(', ')});
  if(e.winner && (!roster.has(e.winner) || /^Qualifier \d+$/.test(e.winner))){anonymousChampions++;if(e.type!=='Q School'&&e.type!=='Exhibition'&&!/qualif(?:ier|ication|ying)|play[ -]?off/i.test(e.name))anonymousTitles++;eventAnomalies.push({kind:'anonymous-champion',detail:e.name+': '+e.winner});}
  const ageLimit=/under[ -]?16|\bu16\b/i.test(e.name)?16:/under[ -]?18|\bu18\b/i.test(e.name)?18:/wsf junior/i.test(e.name)?19:/under[ -]?21|\bu21\b/i.test(e.name)?21:['Junior','Regional Youth','National Youth'].includes(e.type)?21:null;
  for(const name of names){const player=roster.get(name); if(!player || name===d.human.name)continue; const age=player.age-1;
   if((ageLimit && age>=ageLimit)||(e.type==='Senior' && age<40)){ageViolations++;eventAnomalies.push({kind:'field-age',detail:e.name+': '+name+', age '+age});}}
  const qualifiers=/^qSchool(Uk|Asia)|qTourPlayoff/.test(e.format??'')?(e.bracket.at(-1)?.matches??[]).filter(m=>typeof m.top.score==='number'&&typeof m.bottom.score==='number').map(m=>m.top.score>m.bottom.score?m.top.name:m.bottom.name):[];
  for(const name of qualifiers){const player=roster.get(name);qualificationRows.push({event:e.name,name,card:player?.card??false});if(player && !/^Qualifier \d+$/.test(name)){namedQualifications++;if(!player.card){missingCards++;eventAnomalies.push({kind:'qualifier-without-card',detail:e.name+': '+name});}}}

  eventCsv.push([d.season,e.name,e.type,e.format,e.date,e.ranking,e.entrants,e.scoredMatches,e.winner,e.final,qualifiers.join('; ')]);
  for(const r of e.bracket)for(const m of r.matches){if(m.placeholder||typeof m.top.score!=='number'||typeof m.bottom.score!=='number')continue;
   for(const [p,q] of [[m.top,m.bottom],[m.bottom,m.top]]){if(p.name==='TBD')continue;const x=get(p.name);x.matches++;if(p.score>q.score)x.wins++;else if(p.score<q.score)x.losses++;else x.draws++;}}
  if(e.winner && e.type!=='Q School' && e.type!=='Exhibition' && !/qualif(?:ier|ication|ying)|play[ -]?off/i.test(e.name)){get(e.winner).titles++;if(roster.has(e.winner) && !/^Qualifier \d+$/.test(e.winner))titleCounts.set(e.winner,(titleCounts.get(e.winner)||0)+1);actualTitleTotals.set(e.winner,(actualTitleTotals.get(e.winner)||0)+1);
   if(majorNames.includes(e.name)){get(e.winner).majors++;actualMajorTotals.set(e.winner,(actualMajorTotals.get(e.winner)||0)+1);}
   if(e.name==='World Championship')worldCounts.set(e.winner,(worldCounts.get(e.winner)||0)+1);}
 }
 const anomalies=[...eventAnomalies], growth={prospects:[],prime:[],veterans:[]};
 for(const p of d.roster){
  const a=actual.get(p.name),r=p.seasonRecord,old=previousRoster?.get(p.name);
  if(p.name!==d.human.name&&r&&r.matches<r.wins+r.losses){mismatchedRecords++;anomalies.push({kind:'cpu-record-arithmetic',detail:p.name+': stored '+r.matches+' matches, '+r.wins+' wins, '+r.losses+' losses'+(a?'; actual bracket '+a.matches+' matches':'' )});}
  if(p.name!==d.human.name&&actualMajorTotals.get(p.name)>p.majors){majorCountMissing++;anomalies.push({kind:'major-title-counter',detail:p.name+': '+actualMajorTotals.get(p.name)+' observed major wins, stored '+p.majors});}
  if(p.name!==d.human.name&&a?.matches>0&&p.highestBreak===0)breakCountMissing++;
  if(old&&!old.retired&&!p.retired&&p.ratingChange!==null){const band=old.age<=25?'prospects':old.age>=40?'veterans':'prime';growth[band].push(p.ratingChange);}
  playerCsv.push([d.season,p.id,p.name,p.nation,p.age,p.retired,p.card,p.cardSource,p.rating,p.potential,p.ratingChange,p.skillOffsets?.longPotting,p.skillOffsets?.breakBuilding,p.skillOffsets?.safetyPlay,p.skillOffsets?.composure,p.skillOffsets?.stamina,r?.worldRank,r?.matches,r?.wins,r?.losses,a?.matches,a?.wins,a?.losses,a?.draws,p.titles,a?.titles,p.majors,a?.majors,p.prize,p.highestBreak]);
 }
 for(const x of [...d.issues,...anomalies])issueCsv.push([d.season,x.kind,x.detail]);
 invalidScores+=d.issues.filter(x=>['invalid-score','frame-format','unresolved-match'].includes(x.kind)).length;
 const active=d.roster.filter(p=>!p.retired), top=d.rankings.slice(0,10), topNames=new Set(top.map(p=>p.playerName));
 const champion=d.events.find(e=>e.name==='World Championship')?.winner;
 if(top[0])numberOnes.set(top[0].playerName,(numberOnes.get(top[0].playerName)||0)+1);
 const youthAges=Object.values(d.nextSeasonTables.youth?.top10??[]).map(r=>roster.get(r.playerName)?.age).filter(x=>x!==undefined);
 const row={season:d.season,startedOn:d.startedOn,endedOn:d.endedOn,expected:d.expectedEvents,events:d.events.length,matches:d.events.reduce((n,e)=>n+e.scoredMatches,0),
   active:active.length,retired:d.roster.length-active.length,roster:d.roster.length,newcomers:d.newcomers.length,namedNewcomers:d.newcomers.filter(p=>!/^Qualifier \d+$/.test(p.name)).length,retirements:d.retirements.length,
   cards:active.filter(p=>p.card).length,cardsGained:d.cardsGained.length,cardsLost:d.cardsLost.length,
   ageAverage:average(active.map(p=>p.age)),ageMin:Math.min(...active.map(p=>p.age)),ageMax:Math.max(...active.map(p=>p.age)),
   ratingAverage:average(active.map(p=>p.rating).filter(Number.isFinite)),rating95:active.filter(p=>p.rating>=95).length,
   originalActive:active.filter(p=>initialNames.has(p.name)).length,top10New:top.filter(p=>!initialNames.has(p.playerName)).length,
   top10Turnover:seasons.length?top.filter(p=>!seasons.at(-1).top.some(q=>q.playerName===p.playerName)).length:null,
   top10AverageAge:average(top.map(p=>roster.get(p.playerName)?.age-1).filter(Number.isFinite)),champion,championAge:roster.get(champion)?.age-1,championNew:champion?!initialNames.has(champion):null,
   top,majors:d.events.filter(e=>majorNames.includes(e.name)).map(e=>({name:e.name,winner:e.winner,final:e.final})),
   circuitSizes:Object.fromEntries(Object.entries(d.nextSeasonTables).map(([k,v])=>[k,v.size])),
   nextCircuitLeaders:Object.fromEntries(Object.entries(d.nextSeasonTables).map(([k,v])=>[k,v.top10[0]?.playerName??'—'])),
   growth:Object.fromEntries(Object.entries(growth).map(([k,v])=>[k,{count:v.length,average:average(v)}])),
   topGainers:active.filter(p=>p.ratingChange!==null).sort((a,b)=>b.ratingChange-a.ratingChange).slice(0,5).map(p=>({name:p.name,age:p.age,delta:p.ratingChange,rating:p.rating})),
   topDecliners:active.filter(p=>p.ratingChange!==null).sort((a,b)=>a.ratingChange-b.ratingChange).slice(0,5).map(p=>({name:p.name,age:p.age,delta:p.ratingChange,rating:p.rating})),
   retirementNames:d.retirements.map(p=>p.name+' (age '+p.age+')'),newcomerNames:d.newcomers.map(p=>p.name+' ('+p.age+', '+p.nation+')'),
   cardGainNames:d.cardsGained.map(p=>p.name+' — '+p.cardSource),cardLossNames:d.cardsLost.map(p=>p.name),
   human:d.human,qualifications:qualificationRows,issues:d.issues,derivedAnomalies:anomalies.length,duplicateYouthAges:youthAges.filter(a=>a>21),memoryMb:d.memoryMb};
 seasons.push(row);expected+=d.expectedEvents;completed+=d.events.length;matches+=row.matches;previousRoster=roster;
}
const final=seasons.at(-1), first=seasons[0];
const ranked=m=>[...m].sort((a,b)=>b[1]-a[1]);
const summary={seasons:seasons.length,weeklySettlements:managed?.weeksSimulated,managedEntries:managed?.tournamentsEntered,managedHarnessFlags:managed?.issues.length,firstDate:first.startedOn,lastDate:final.endedOn,firstNewTop10Season:seasons.find(s=>s.top10New>0)?.season,firstNewChampion:seasons.find(s=>s.championNew)?.champion,firstNewChampionSeason:seasons.find(s=>s.championNew)?.season,totalNewcomers:seasons.reduce((n,s)=>n+s.newcomers,0),namedNewcomers:seasons.reduce((n,s)=>n+s.namedNewcomers,0),totalRetirements:seasons.reduce((n,s)=>n+s.retirements,0),cardHoldersMin:Math.min(...seasons.map(s=>s.cards)),cardHoldersMax:Math.max(...seasons.map(s=>s.cards)),negativeClosingSeasons:seasons.filter(s=>s.human.closingCash<0).length,meanChampionAge:average(seasons.map(s=>s.championAge).filter(Number.isFinite)),youngestChampionAge:Math.min(...seasons.map(s=>s.championAge).filter(Number.isFinite)),oldestChampionAge:Math.max(...seasons.map(s=>s.championAge).filter(Number.isFinite)),expectedEvents:expected,completedEvents:completed,scoredMatches:matches,scoreRuleFlags:invalidScores,rawIssuesByKind,retiredNamedFlags,worldChampions:ranked(worldCounts),numberOnes:ranked(numberOnes),titles:ranked(titleCounts),anonymousChampions,anonymousTitles,fillerEntries,eventsBeyondRollover,ageViolations,namedQualifications,missingCards,cpuRecordArithmeticRows:mismatchedRecords,cpuMajorCounterRows:majorCountMissing,cpuZeroBreakRows:breakCountMissing,final};
writeCsv('seasons.csv',['Season','Events','Expected','Matches','World champion','Champion age','No. 1','Active players','Retirements','Newcomers','Card holders','Cards gained','Cards lost','Mean rating','95+ ratings','Mean age','Original active','Newcomers top ten'],seasons.map(s=>[s.season,s.events,s.expected,s.matches,s.champion,s.championAge,s.top[0]?.playerName,s.active,s.retirements,s.newcomers,s.cards,s.cardsGained,s.cardsLost,s.ratingAverage,s.rating95,s.ageAverage,s.originalActive,s.top10New]));
writeCsv('tournaments.csv',['Season','Tournament','Circuit','Format','Completion date','Ranking','Entrants','Scored matches','Winner','Final','Q School / playoff qualifiers'],eventCsv);
writeCsv('players.csv',['Season','ID','Name','Nation','Age at next opening','Retired','Tour card','Card source','Rating','Potential','Rating change','Long pot offset','Break offset','Safety offset','Composure offset','Stamina offset','Archived world rank','Stored season matches','Stored wins','Stored losses','Actual bracket matches','Actual wins','Actual losses','Actual draws','Stored career titles','Observed season titles','Stored career majors','Observed season majors','Career prize','Highest break'],playerCsv);
writeCsv('rankings.csv',['Season','Circuit','Snapshot timing','Rank','Name','Points','Events played','Wins','Losses','Titles'],rankingCsv);
writeCsv('findings.csv',['Season','Check','Evidence'],issueCsv);
fs.writeFileSync(path.join(out,'summary.json'),JSON.stringify({summary,seasons},null,2));
const line=[];const put=s=>line.push(s);const table=(heads,rows)=>{put('| '+heads.join(' | ')+' |');put('| '+heads.map(()=>'---').join(' | ')+' |');for(const r of rows)put('| '+r.map(v=>String(v??'—').replaceAll('|','/')).join(' | ')+' |');put('');};
put('# 50-year snooker world audit');put('');
put(managed ? 'Run: fixed seed **20260906**, current local game code, managed rookie professional starting at age 21 with a two-year test card, rank 100 and £6,000. Conservative authored career choices, middle support, normal weekly settlement, travel, preparation and quick-sim match actions. This is a separate career, not the live RT save.' : 'Run: seed **20260906**, annual world regression using the production CPU calendar and season rollover. The human skips all events. This checks all tournament fields, scores, rankings, cards, records, ageing and population; it does not test 50 years of human finances, travel or weekly training. The original managed-career baseline is preserved separately.');put('');
put('**Completed '+seasons.length+' seasons: '+first.startedOn+' to '+final.endedOn+'.** The opening career starts in May, so the first archive is longer than subsequent annual sporting seasons. One seeded run tests longevity and invariants, not the full range of random outcomes or real-world sporting realism.');put('');
put('## Verdict and findings');put('');put(managed ? 'The calendar and world continued through the recorded seasons, but the world should not be considered fully correct. Confirmed recordkeeping inconsistencies and event omissions are detailed below. No game-balance or simulation fixes were applied during this baseline.' : 'Post-fix world regression. The measurements below compare persistent records against completed brackets. Changes include calendar ownership, eligible recruitment, earned cards, CPU statistics and age-dependent ability.');put('');
table(['Measure','Observed'],[['Completed / expected tournament records',fmt(completed)+' / '+fmt(expected)],['Scored bracket matches',fmt(matches)],['Weekly settlements',managed ? fmt(managed.weeksSimulated) : 'Not part of this test'],['Managed-player tournament entries',managed?.tournamentsEntered??'Not available'],['Distinct World Champions',worldCounts.size],['Distinct closing world number ones',numberOnes.size],['World champion age range / mean',summary.youngestChampionAge+'–'+summary.oldestChampionAge+' / '+fmt(summary.meanChampionAge)],['Tour-card holders each rollover',Math.min(...seasons.map(s=>s.cards))+'–'+Math.max(...seasons.map(s=>s.cards))],['Named new players introduced',fmt(seasons.reduce((n,s)=>n+s.namedNewcomers,0))],['All new roster profiles (including fillers)',fmt(seasons.reduce((n,s)=>n+s.newcomers,0))],['Retirements',fmt(seasons.reduce((n,s)=>n+s.retirements,0))],['Final active / total roster',final.active+' / '+final.roster],['Frame-score / unresolved match flags',invalidScores],['Finals won by anonymous entries (includes qualifiers)',anonymousChampions],['Title-awarding finals won by anonymous entries',anonymousTitles],['Recorded events dated after their season review',eventsBeyondRollover],['Generic / non-persistent entrant appearances',fmt(fillerEntries)],['Age-ineligible roster entrant appearances',ageViolations],['Named Q School / playoff qualifiers receiving cards',(namedQualifications-missingCards)+' / '+namedQualifications],['Player-season records with matches < wins + losses',fmt(mismatchedRecords)],['Player-season major-counter shortfalls',fmt(majorCountMissing)],['Active CPU player-season rows with highest break 0',fmt(breakCountMissing)]]);
if(managed) {
put('1. **CPU match totals are unreliable.** Archived matches sum events played while wins/losses sum matches. This is a source-confirmed arithmetic defect at src/hooks/useGameState.ts, in archiveWorldPlayersForSeason. The players CSV contains both the stored numbers and results counted directly from completed brackets.');put('2. **CPU major-title counters do not reflect observed winners.** The season archive adds major titles only for the human player. Tournament winner tables in this report use actual finals instead.');put('3. **Championship League crosses the season boundary and loses results.** Its authored schedule is 30 June–23 July. Schedule generation assigns it using its June start, but rollover replaces that calendar on 1 July. This source-confirmed mismatch explains repeated missing ledger records; absence does not prove that no group fixtures were played.');
put('4. **Anonymous entrants can win finals.** '+anonymousChampions+' final winners (including qualifying finals) in this run are generic Qualifier entries or absent from the persistent roster; '+anonymousTitles+' were title-awarding events. '+fmt(fillerEntries)+' generic or non-persistent entrant appearances were observed across the fields. Regional and youth recruitment does not consistently supply complete named fields; these fillers cannot develop normal careers.');put('5. **Earned tour cards can be dropped.** '+missingCards+' named Q School/playoff qualification results did not produce a next-season card. The allocation sorts earned-card candidates and takes only available slots, so a valid qualifying result can be discarded when too many existing cards are protected. Individual names and seasons are in findings.csv.');
put('6. **Age-invalid filler profiles appear in youth events.** '+ageViolations+' roster-entry appearances fail the configured age check. These need to be read alongside generic Qualifier profiles: matching placeholder names can collide with persistent filler records and bypass normal eligibility.');
put('7. **Break records are incomplete.** CPU highest-break values of zero are not evidence that those players never made a scoring break. This run cannot validate CPU century/maximum statistics from the available aggregate brackets.');put('8. **Duplicate ranking rows, if present, are listed separately.** These are raw audit flags; all-circuit ranking rows were checked after rollover, while the world top ten is a frozen closing snapshot.');put('');
} else { put('The original baseline defects were checked again below. CPU breaks are additional simulated match records, not measured real-world shot data; legacy missing break records remain unknown. Protected contractual cards are honoured even in an overfull legacy field; newly issued discretionary top-ups last one season.'); put(''); }
put('## Integrity checks');put('');table(['Check','Observed flags'],[['Invalid / unresolved / wrong-frame scores',invalidScores],['Duplicate persistent IDs or names',rawIssuesByKind['duplicate-player']??0],['Incorrect annual age increment',rawIssuesByKind['age-increment']??0],['Non-finite numeric values',rawIssuesByKind['non-finite']??0],['Ratings outside 0–100',rawIssuesByKind['rating-range']??0],['World ranking order / points order',(rawIssuesByKind['ranking-order']??0)+(rawIssuesByKind['ranking-points-order']??0)],['Retired profiles retaining tour cards',rawIssuesByKind['retired-card']??0],['Retired ordinary named entrants',retiredNamedFlags],['Retired-name field flags (includes generic identities)',rawIssuesByKind['retired-entry']??0],['Duplicate circuit ranking rows',rawIssuesByKind['duplicate-ranking']??0]]);put('These are invariant checks against the configured game model. Zero flags do not establish that real-world formats, prize distributions or balance are correct.');put('');
put('## Downloads and evidence');put('');for(const [f,l]of [['seasons.csv','Every season'],['tournaments.csv','Every recorded tournament and final'],['players.csv','Every player-season, development and record comparison'],['rankings.csv','All captured rankings across every circuit'],['findings.csv','Every flagged record and its evidence'],['summary.json','Structured summary and per-season detail'],...(managed ? [['managed-career-report.md','Original managed-career report and harness warnings']] : []),['run-manifest.json','Test source fingerprint and command']])put('- ['+l+']('+path.join(out,f).replaceAll('\\','/')+')');put('');
put('## All seasons');put('');table(['Season','Events','Matches','World Champion (age)','No. 1','Active','In / retired','Cards gained / lost'],seasons.map(s=>[s.season,s.events+'/'+s.expected,fmt(s.matches),s.champion+' ('+s.championAge+')',s.top[0]?.playerName,s.active,s.newcomers+' / '+s.retirements,s.cardsGained+' / '+s.cardsLost]));
put('## Championship and ranking leadership');put('');table(['World champion','Titles in this run'],ranked(worldCounts));table(['Closing world number one','Seasons'],ranked(numberOnes));
put('The first generated player reached the closing top ten in '+summary.firstNewTop10Season+'. '+summary.firstNewChampion+' became the first generated World Champion in '+summary.firstNewChampionSeason+'. All '+final.top10New+' of the final top ten were generated after the start.');put('');
put('## Generational development');put('');table(['Season','Mean active age','Mean rating','95+ ratings','Original active','New generation in top ten','Prospect Δ','Veteran Δ'],seasons.map(s=>[s.season,fmt(s.ageAverage),fmt(s.ratingAverage),s.rating95,s.originalActive,s.top10New,fmt(s.growth.prospects.average),fmt(s.growth.veterans.average)]));put('Ratings are actual saved overall ratings. Changes compare consecutive opening snapshots for players who remained active; prospects were aged 25 or younger and veterans 40 or older at the previous opening. First-season cohort averages are unavailable and shown as zero. Skill offsets are additional modifiers, exported separately.');put('');
put('The rankings CSV contains the frozen closing world standings and all other circuit standings captured before the final calendar advance. The latter can be up to one week before rollover, so they are labelled separately.');put('');
put('## Every circuit at rollover');put('');table(['Season','World','One-year','Q Tour','Q School','Amateur','Youth','Seniors'],seasons.map(s=>[s.season,...['world','oneYear','qTour','qSchool','amateur','youth','senior'].map(k=>s.circuitSizes[k])]));
if(managed) { put('## Managed player career and finances');put('');table(['Season','Age at next opening','Record','Titles','Prize','Closing cash','Tour card'],seasons.map(s=>[s.season,s.human.age,(s.human.record?.wins??0)+'–'+(s.human.record?.losses??0),s.human.record?.titles,'£'+fmt(s.human.record?.prizeMoney??0),'£'+fmt(s.human.closingCash),s.human.card.hasTourCard?'Yes':'No']));put('Cash is the actual saved balance; prize is the archived season prize. Negative cash and passive years must be interpreted in the context of the automated management policy and the detailed managed-career report. This audit does not reconcile every individual transaction.');put('');
}
put('## Detailed season dossiers');put('');for(const s of seasons){put('### '+s.season);put('');put(s.startedOn+' → '+s.endedOn+' · '+s.events+'/'+s.expected+' event records · '+fmt(s.matches)+' scored matches · '+s.active+' active players · '+s.cards+' tour cards.');put('');table(['Major','Winner','Final'],s.majors.map(e=>[e.name,e.winner,e.final]));table(['Closing rank','Player','Ranking points'],s.top.map(r=>[r.ranking,r.playerName,fmt(r.points)]));if(s.qualifications.length)table(['Qualification event','Player','Card at next opening'],s.qualifications.map(q=>[q.event,q.name,q.card?'Awarded':'Missing']));
put('**Largest rating gains:** '+s.topGainers.map(p=>p.name+' '+(p.delta>=0?'+':'')+p.delta+' → '+p.rating).join('; ')+'.');put('');put('**Largest rating falls:** '+s.topDecliners.map(p=>p.name+' '+(p.delta>=0?'+':'')+p.delta+' → '+p.rating).join('; ')+'.');put('');put('**Newcomers:** '+(s.newcomerNames.join('; ')||'None')+'.');put('');put('**Retirements:** '+(s.retirementNames.join('; ')||'None')+'.');put('');put('**Cards gained:** '+(s.cardGainNames.join('; ')||'None')+'.');put('');put('**Cards lost:** '+(s.cardLossNames.join('; ')||'None')+'.');put('');if(s.issues.length)put('**Raw integrity flags:** '+s.issues.map(x=>x.kind+': '+x.detail).join('; ')+'.');put('**Derived record discrepancies:** '+s.derivedAnomalies+'. See findings.csv for individual rows.');put('');}
put('## Limits of this test');put('');put(managed ? 'This is one seeded managed-career endurance run. It exercises normal world-calendar processing, quick-sim matches and rollovers, but not every live-match UI action, save/reload after 50 years, every travel choice or every starting-career scenario. CPU aggregate brackets do not provide a complete shot-level record for pot percentages, centuries or maximums. The separate managed-career report also contains older harness warnings; those are raw flags, not all independently confirmed game defects.' : 'This is one seeded CPU-world regression using annual calendar processing. Human finances and weekly play require separate managed-career tests. Match scores and statistical invariants are checked against the game model, not independently researched sporting rules. CPU break records are simulated estimates, and missing legacy data is not reconstructed. The additional two-season managed run exercised 111 weekly settlements and 23 entries; its fixed spending policy briefly reached −£27. Cash warnings and club work are tested separately.');put('');
if(managed) { put('## Recommended repair order');put('');put('1. Fix Championship League season ownership and carry-over before changing the calendar further.');put('2. Reconcile retained, protected and newly earned tour cards before filling the 128-player field; never discard a qualifying result silently.');put('3. Generate enough persistent, eligible players for each region and youth age band; use stable IDs and eliminate generic-name collisions.');put('4. Build CPU match totals and major-title counters from the same recorded results, with draws handled explicitly.');put('5. Remove duplicate circuit ranking rows, then rerun this seed plus additional seeds and starting careers.');put('6. Review debt handling and CPU break-stat completeness separately from the world-calendar fixes.');put('');
put('## Reproduction');put('');put('Run: npx tsx scripts/simulateFiveSeasons.ts --seasons=50 --rookie-pro-21 --seed=20260906 --skip-player-snapshots --skip-shared-audits --world-audit');put('');put('Then: node scripts/summarizeWorldAudit.cjs '+source);put('');put('Raw season JSON files preserve the complete observed brackets and roster. No real-world rules or player database were substituted for this test. The audit tests the rules configured in this build; it is not a fresh external verification of tournament regulations.');
}
fs.writeFileSync(path.join(out,'50-year-world-report.md'),line.join('\n'));
console.log(JSON.stringify({...summary,final:undefined,report:path.join(out,'50-year-world-report.md')},null,2));
