import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {encodeCareerSave,decodeCareerSave} from '../src/game/saveStorage';
import {repairGameState,type GameState} from '../src/hooks/useGameState';
import {rebuildRollingRankings} from '../src/game/rollingRankings';
const source=process.argv[2];if(!source)throw new Error('Supply isolated century save');
const out=process.argv[3]??'artifacts/century-20260911/save-verification.json';
const raw=fs.readFileSync(source,'utf8'),s=JSON.parse(decodeCareerSave(raw)) as GameState;
const hash=(x:string)=>crypto.createHash('sha256').update(x).digest('hex');
const results:Record<string,unknown>={source,pathHash:hash(raw),date:s.currentDate,age:s.player.age,seasons:s.history.seasonRecords.length,rawBytes:Buffer.byteLength(raw),timings:{}};
const time=<T>(name:string,fn:()=>T)=>{const start=performance.now(),v=fn();(results.timings as Record<string,number>)[name]=Math.round(performance.now()-start);return v;};
const encoded=time('encodeMs',()=>encodeCareerSave(s));
results.compressedStorageBytes=encoded.length*2;
results.compressedUtf8Bytes=Buffer.byteLength(encoded);
results.lossless=time('decodeMs',()=>decodeCareerSave(encoded)===JSON.stringify(s));
const keyState=(x:GameState)=>({date:x.currentDate,season:x.season,age:x.player.age,cash:x.player.cash,legacy:x.history.legacy,seasons:x.history.seasonRecords,life:x.careerDepth?.seasonLife,contracts:x.coachContracts,card:x.careerSystems.pro,ledger:x.finance.ledger,world:x.worldPlayers.map(p=>({id:p.id,age:p.age,retired:p.retired,card:p.hasTourCard,titles:p.titles,majors:p.majorTitles,matches:p.totalMatches,wins:p.wins,losses:p.losses,prize:p.totalPrizeMoney})),matches:x.matches.map(m=>m.id)});
const differences=(a:Record<string,unknown>,b:Record<string,unknown>)=>Object.keys(a).filter(k=>JSON.stringify(a[k])!==JSON.stringify(b[k]));
const repaired=time('firstRepairMs',()=>repairGameState(s));
const second=time('secondRepairMs',()=>repairGameState(repaired));
results.firstRepairChanged=differences(keyState(s),keyState(repaired));
results.secondRepairChanged=differences(keyState(repaired),keyState(second));
results.cash=[s.player.cash,repaired.player.cash,second.player.cash];
const rebuilt=time('rankingRebuildMs',()=>rebuildRollingRankings(s,s.currentDate,false));
results.rankingDifferences=Object.fromEntries((['world','oneYear'] as const).map(key=>[key,s.competitionTables[key].filter((r,i)=>{const n=rebuilt.competitionTables[key][i];return !n||r.playerName!==n.playerName||r.points!==n.points||r.ranking!==n.ranking;}).map(r=>({name:r.playerName,rank:r.ranking,points:r.points,rebuilt:rebuilt.competitionTables[key].find(x=>x.playerName===r.playerName)}))]));
results.sourceUnchanged=hash(fs.readFileSync(source,'utf8'))===hash(raw);
fs.mkdirSync(path.dirname(out),{recursive:true});fs.writeFileSync(out,JSON.stringify(results,null,2));console.log(JSON.stringify(results,null,2));
