import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import {getTournamentEntryAccess,type GameState} from '../src/hooks/useGameState';
import {alignMajorSelection,lockTournamentSeedings,rankingEventKey} from '../src/game/rollingRankings';
import {championInvitations} from '../src/game/championInvitations';
import {buildTitleSummary,repairAuditTournamentFlags,buildBalanceWarnings} from './simulateFiveSeasons';
import {serializeCareerSave} from '../src/game/asyncSave';
const dir=process.argv[2];if(!dir)throw new Error('Supply the frozen audit simulations directory');
const names=fs.readdirSync(dir),saveName=names.find(n=>n.endsWith('-save.json'))!,checkpoint=names.find(n=>n.endsWith('-checkpoint-25.json'))!;
const file=path.join(dir,saveName),raw=fs.readFileSync(file,'utf8'),state=JSON.parse(raw) as GameState;
const report=JSON.parse(fs.readFileSync(path.join(dir,saveName.replace('-save.json','.json')),'utf8'));
const old=JSON.parse(fs.readFileSync(path.join(dir,checkpoint),'utf8')) as GameState;
const person=old.player.fullName;
const dates=['2051-03-31','2051-04-11'];
const originalSelection=dates.map(date=>({date,rank:[...old.rollingRankings!.revisions].reverse().find(r=>r.date<=date)?.world[person]}));
assert.deepEqual(originalSelection.map(r=>r.rank),[13,17]);
const tournaments=old.tournaments.filter(t=>/world championship/i.test(t.name)).map(t=>({...t,startDate:t.startDate.replace('2052','2051'),endDate:t.endDate?.replace('2052','2051'),seedingCutoffDate:undefined,status:'Available' as const}));
let replay={...old,season:'2050/51',currentDate:'2051-04-03',tournaments,rollingRankings:{...old.rollingRankings!,seedings:{}}};
replay=lockTournamentSeedings(replay,replay.currentDate);
replay={...replay,currentDate:'2051-04-18',player:{...replay.player,worldRanking:17}};
const main=replay.tournaments.find(t=>t.formatId==='worldChampionshipMain')!;
assert.equal(replay.rollingRankings!.seedings[rankingEventKey(main)].world[person],13);
assert.equal(getTournamentEntryAccess(replay,main).allowed,true);
assert.equal(alignMajorSelection(replay),replay);
const championship={...state.tournaments.find(t=>t.formatId==='championOfChampions')!,status:'Available' as const};
const rejectedYears=[];
for(let y=2065;y<=2075;y++){
 const copy={...state,currentDate:`${y}-11-01`};
 const event={...championship,startDate:`${y}-11-09`,seedingCutoffDate:undefined};
 assert.equal(championInvitations(copy,event).names.includes(state.player.fullName),false);
 assert.equal(getTournamentEntryAccess(copy,event).allowed,false);
 rejectedYears.push(`${y}/${String(y+1).slice(-2)}`);
}
const before=report.seasons.flatMap((s:{tournaments:Parameters<typeof buildTitleSummary>[0]})=>s.tournaments);
const titles=buildTitleSummary(before);
assert.equal(titles.totalTitles,state.history.legacy!.trophies.filter(t=>t.category!=='Exhibition').length);
assert.equal(titles.totalTitles,92);
const corrected={...report,seasons:report.seasons.map((s:{tournaments:Parameters<typeof buildTitleSummary>[0]})=>({...s,tournaments:s.tournaments.map(repairAuditTournamentFlags)}))};
const warnings=buildBalanceWarnings(corrected,state);
assert(!warnings.some(w=>/No-tour player earned world ranking prize money/.test(w)));
const serialized=await serializeCareerSave(state);
assert.equal(serialized,JSON.stringify(state));
const hash=(v:string)=>crypto.createHash('sha256').update(v).digest('hex');
assert.equal(hash(fs.readFileSync(file,'utf8')),hash(raw));
const result={source:saveName,originalSelection,fixedSelection:replay.rollingRankings!.seedings[rankingEventKey(main)].world[person],worldEntryAllowed:true,rejectedOldTitleYears:rejectedYears,titles,excludedFalseTitles:before.filter((t:Parameters<typeof repairAuditTournamentFlags>[0])=>t.countedInTotalTitleRecord&&!repairAuditTournamentFlags(t).countedInTotalTitleRecord).map((t:Parameters<typeof repairAuditTournamentFlags>[0])=>({name:t.name,result:t.result,date:t.startDate})),deciders:{previousReport:report.supportMetrics.deciderMatches,saved:state.history.legacy!.deciders,savedWins:state.history.legacy!.decidersWon},oldFalseMoneyWarning:report.balanceWarnings.filter((w:string)=>/world ranking prize money/.test(w)),remainingWarnings:warnings,chunkedSerializationLossless:true,sourceUnchanged:true};
fs.mkdirSync('artifacts/long-save-fixes',{recursive:true});fs.writeFileSync('artifacts/long-save-fixes/snapshot-verification.json',JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));
