import { getDefaultPreparationAllocations } from '../tournamentPreparation';
import { replayTeamFoul } from './live';
import { afterEach, describe, expect, it, vi } from 'vitest';
import { getNextEligibleTournament, enterTournamentState, bookTravelState, confirmTournamentPreparationState, continueToNextTournamentState, simulateTournamentMatchState, createStarterState, createTeamLiveMatch, advanceLiveVisit, resolveCompletedLiveFrame, finalizeLiveMatch, repairGameState, hireCoachState, type GameState } from '../../hooks/useGameState';
import { initializeSeasonLife, reconcileSeasonLife, seasonLifeAction, seasonLifeTraining } from './index';
import { diagnoseForm, emptyEvidence, recordForm, settleFormDate, formLiveAdjustment } from './form';
import { lifeStory, lifeOf, putLife } from './shared';
import { staffChoice, reconcileStaff, staffUnavailable } from './staff';
import { startTeamMatch, availableTeamMember, member, offerTeam, teamChoice, teamConflict, settleTeamMatch, simulateTeamRubber } from './teams';
import { offerInterview, answerInterview } from './media';
import { depthOf, plusDays } from '../careerDepth/shared';
import type { FormEvidence, TeamEvent } from './types';
import { buildTrainingCell } from '../../utils/trainingPlan';
const initial=createStarterState();
function career(){const s=structuredClone(initial);s.careerDepth={...depthOf(s),seasonLife:undefined};s.matches=[];s.inbox=[];s.player.cash=50000;return initializeSeasonLife(s);}
function evidence(openingsMade:number,leadsLost=0):FormEvidence{return {openings:10,openingsMade,strongLeads:2,leadsLost};}
function issue(s=career()) {let next=s;for(let i=0;i<6;i++) next=recordForm(next,{...initial.matches[0],id:'e'+i,playedOn:plusDays(s.currentDate,i),formEvidence:evidence(i<3?9:2)});return next;}
function pairs(s=career()):{s:GameState;e:TeamEvent}{
 const candidates=s.worldPlayers.filter(p=>p.playerName!==s.player.fullName).slice(0,7);candidates.forEach(p=>{p.retired=false;p.injuryWeeks=0;p.hasTourCard=false;p.age=18;});
 const members=[member(s,s.player.id),...candidates.map(p=>member(s,p.id))];
 const teams=Array.from({length:4},(_,i)=>({name:'Named pair '+i,members:[members[i*2],members[i*2+1]] as [typeof members[0],typeof members[0]]}));
 const e:TeamEvent={id:'team-fixture',name:'Youth Club Pairs',kind:'youth',season:s.season,cutoff:s.currentDate,start:plusDays(s.currentDate,14),end:plusDays(s.currentDate,15),deadline:plusDays(s.currentDate,11),status:'accepted',accepted:s.currentDate,teams,partnerOptions:[members[1]],ties:[{home:0,away:1,results:[]},{home:2,away:3,results:[]}],fee:25,travel:100,support:100,winnerShare:250,runnerUpShare:100};
 return {s:putLife(s,{...lifeOf(s),teams:[e]}),e};
}
function random(seed=27){vi.spyOn(Math,'random').mockImplementation(()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296;});}
function finish(live:ReturnType<typeof createTeamLiveMatch>){for(let i=0;i<6000&&live.status==='In Progress';i++)live=advanceLiveVisit(live,undefined,'simulated');expect(live.status).toBe('Completed');return live;}
afterEach(()=>vi.restoreAllMocks());
describe('neutral migration and bounded incremental records',()=>{
 it('does not replay historical matches, money, contracts or interviews',()=>{const s=structuredClone(initial);s.careerDepth={...depthOf(s),seasonLife:undefined};const next=initializeSeasonLife(s);expect(next.player).toEqual(s.player);expect(next.finance).toEqual(s.finance);expect(next.coachContracts).toEqual(s.coachContracts);expect(lifeOf(next).evidence).toEqual([]);expect(lifeOf(next).interviews).toEqual([]);expect(initializeSeasonLife(next)).toBe(next);expect(reconcileSeasonLife(next)).toBe(next);});
 it.each(['before','after','project','expiry'])('repeated repair around %s is financially idempotent',kind=>{const s=career();if(kind==='project')s.careerDepth!.project={id:'old',kind:'cue-action',startedDate:s.currentDate,reviewDate:plusDays(s.currentDate,42),completedWeeks:1,status:'active',note:'Preserved',baseline:{Consistency:70},evidenceMatches:0};if(kind==='expiry')s.coachContracts=s.coachContracts.map(c=>({...c,weeksRemaining:1}));if(kind==='after')s.matches=[initial.matches[0]];s.careerDepth!.seasonLife=undefined;const a=repairGameState(s),b=repairGameState(JSON.parse(JSON.stringify(a)));expect(b.player.cash).toBe(a.player.cash);expect(b.finance.ledger).toEqual(a.finance.ledger);expect(b.careerDepth?.project).toEqual(a.careerDepth?.project);expect(b.careerDepth?.seasonLife?.interviews).toEqual([]);});
 it('retains only fifteen evidence records',()=>{let s=career();for(let i=0;i<40;i++)s=recordForm(s,{...initial.matches[0],id:String(i),formEvidence:evidence(9)});expect(lifeOf(s).evidence).toHaveLength(15);});
});
describe('form diagnosis and recovery',()=>{
 it.each([false,true])('Quick Sim preserves honest evidence with active issue=%s',active=>{let s=career();const t=getNextEligibleTournament(s)!;s=enterTournamentState(s,t.id);s=bookTravelState(s,t.id);s=confirmTournamentPreparationState(s,t.id,'balanced',getDefaultPreparationAllocations(),[]);s=continueToNextTournamentState(s);if(active)s=issue(s);const count=lifeOf(s).evidence.length;random(912);const next=simulateTournamentMatchState(s,t.id);expect(next.matches[0]?.id).not.toBe(s.matches[0]?.id);if(active){expect(next.matches[0].formEvidence).toBeDefined();expect(lifeOf(next).evidence.length).toBe(count+1);}else{expect(next.matches[0].formEvidence).toBeUndefined();expect(lifeOf(next).evidence).toEqual(lifeOf(s).evidence);}});
 it.each([{rows:[]},{rows:[evidence(0)]},{rows:[evidence(9),evidence(9),evidence(0)]}])('requires an established baseline and repeated evidence',({rows})=>expect(diagnoseForm(rows)).toBeUndefined());
 it('does not mistake isolated bad luck for a pattern',()=>expect(diagnoseForm([evidence(9),evidence(9),evidence(9),evidence(9),evidence(9),evidence(0)])).toBeUndefined());
 it('diagnoses sustained long-opening decline and closing problems separately',()=>{expect(lifeOf(issue()).form?.kind).toBe('long-pot');expect(diagnoseForm([evidence(8),evidence(8),evidence(8),evidence(8,1),evidence(8,1),evidence(8,1)])?.kind).toBe('closing');});
 it.each(['training','coach','protect','patience'] as const)('supports %s without an instant cure',route=>{let s=issue();if(route==='coach')s.coachContracts=[{coachId:s.coaches[0].id,slot:'Lead Coach',weeksRemaining:20,startedWeek:s.week,contractWeeks:20,contractLabel:'20 weeks',weeklyCost:100,totalCost:2000}];s=seasonLifeAction(s,{type:'life-recovery',route});expect(lifeOf(s).form?.progress).toBe(0);expect(lifeOf(s).form?.route).toBe(route);const last=s.player;const next=settleFormDate({...s,currentDate:plusDays(s.currentDate,42)});expect(lifeOf(next).form).toBeUndefined();expect(next.player).toEqual(last);});
 it('credits relevant work only once per training week and recovers in three',()=>{let s=seasonLifeAction(issue(),{type:'life-recovery',route:'training'});const plan=s.trainingPlan.map(d=>({...d,competitionName:undefined,morning:buildTrainingCell('long-pot-routine'),afternoon:buildTrainingCell('long-pot-routine'),evening:buildTrainingCell('rest')}));s.trainingCondition.injuryWeeks=0;const first=seasonLifeTraining(s,plan);expect(lifeOf(first).form?.progress).toBe(34);expect(lifeOf(seasonLifeTraining(first,plan)).form?.progress).toBe(34);s=seasonLifeTraining({...first,week:first.week+1},plan);s=seasonLifeTraining({...s,week:s.week+1},plan);expect(lifeOf(s).form).toBeUndefined();});
 it('caps temporary effects and does not stack with a technique rebuild',()=>{const {s,e}=pairs();const live=createTeamLiveMatch(s,e,0,0);delete live.teamContext;live.formIssue=lifeOf(issue()).form;const a=formLiveAdjustment(live);expect(live.playerVisitProfile.longPotting-a.playerVisitProfile.longPotting).toBeLessThanOrEqual(3);expect(formLiveAdjustment({...live,formProjectProtected:true}).playerVisitProfile).toEqual(live.playerVisitProfile);});
 it('preserves recovery on reload and enforces an eight-week episode cooldown',()=>{const s=issue(),loaded=initializeSeasonLife(JSON.parse(JSON.stringify(s)));expect(lifeOf(loaded).form).toEqual(lifeOf(s).form);const recovered=settleFormDate({...loaded,currentDate:plusDays(s.currentDate,42)});const next=issue(recovered);expect(lifeOf(next).form).toBeUndefined();expect(lifeOf(next).formCooldown).toBe(plusDays(s.currentDate,56));});
 it('records opportunity counters from engine decisions, never estimated percentages',()=>{random();const {s,e}=pairs();let live=createTeamLiveMatch(s,e,0,0);delete live.teamContext;live.formEvidence=emptyEvidence();live=advanceLiveVisit(live,'Pot Attempt','manual');expect(live.formEvidence?.openings).toBe(1);expect(live.formEvidence!.openingsMade).toBeLessThanOrEqual(1);});
 it('records an actual lost strong late lead at frame settlement',()=>{const {s,e}=pairs();const live=createTeamLiveMatch(s,e,0,0);live.formEvidence=emptyEvidence();live.formLeadFrame=live.currentFrame;const next=resolveCompletedLiveFrame({...live,playerPoints:40,opponentPoints:80},'Played');expect(next.formEvidence).toMatchObject({strongLeads:1,leadsLost:1});expect(next.formLeadFrame).toBeUndefined();});
});
function renewal(){let s=career();s.coachContracts=[{coachId:s.coaches[0].id,slot:'Lead Coach',weeksRemaining:4,startedWeek:s.week,contractWeeks:4,contractLabel:'4 weeks',weeklyCost:100,totalCost:400}];s=putLife(s,{...lifeOf(s),staff:{}});return reconcileStaff(s);}
describe('staff contracts, junior work and employment',()=>{
 it('provides at least fourteen days notice and honours unanswered contracts',()=>{const s=renewal(),r=lifeOf(s).staff[s.coaches[0].id];expect(Date.parse(r.notice!.deadline)-Date.parse(r.notice!.date)).toBeGreaterThanOrEqual(14*86400000);expect(reconcileStaff(s).coachContracts).toEqual(s.coachContracts);});
 it('does not backdate notice for a legacy one-week contract',()=>{let s=career();s.coachContracts=[{...renewal().coachContracts[0],weeksRemaining:1,endsOn:undefined}];s=putLife(s,{...lifeOf(s),staff:{}});s=reconcileStaff(s);expect(lifeOf(s).staff[s.coaches[0].id].notice).toBeUndefined();});
 it('rejects unaffordable extensions without spending',()=>{const s=renewal();s.player.cash=0;const next=staffChoice(s,s.coaches[0].id,'extend');expect(next.coachContracts).toEqual(s.coachContracts);expect(next.player.cash).toBe(0);expect(next.lastAction).toContain('reserve');});
 it('signs an extension once and leaves billing to the weekly ledger',()=>{const s=renewal(),a=staffChoice(s,s.coaches[0].id,'extend'),b=staffChoice(a,s.coaches[0].id,'extend');expect(a.coachContracts[0].weeksRemaining).toBe(17);expect(b.coachContracts).toEqual(a.coachContracts);expect(a.finance).toEqual(s.finance);});
 it('records unmet facility promises without invalidating the contract',()=>{const s=renewal(),id=s.coaches[0].id,a=staffChoice(staffChoice(s,id,'facilities'),id,'extend');const b=reconcileStaff({...a,currentDate:plusDays(a.currentDate,28),realism:{...a.realism!,base:'club'}});expect(lifeOf(b).staff[id].promise?.met).toBe(false);expect(b.coachContracts).toEqual(a.coachContracts);});
 it('moves an expired coach to a named CPU employer and blocks recruitment',()=>{const s=renewal(),id=s.coaches[0].id;const a=staffChoice(s,id,'decline'),b=reconcileStaff({...a,currentDate:lifeOf(a).staff[id].end!,coachContracts:[]});expect(lifeOf(b).staff[id].employer).toBeTruthy();expect(staffUnavailable(b,id)).toContain('Employed by');expect(hireCoachState(b,id).coachContracts).toHaveLength(0);});
 it('can honour a facility promise and then explicitly extend the same contract',()=>{const s=renewal(),id=s.coaches[0].id,a=staffChoice(s,id,'facilities'),b=staffChoice(a,id,'extend');expect(b.coachContracts[0].weeksRemaining).toBe(17);expect(lifeOf(b).staff[id].promise?.kind).toBe('facilities');});
 it('junior milestone offers an optional responsibility review with a neutral default',()=>{const s=career(),id=s.coaches.find(c=>c.id.startsWith('junior-coach-'))!.id;const l=lifeOf(s),a=putLife(s,{...l,staff:{...l.staff,[id]:{ambition:'methods',experience:12,history:[]}},stories:[{id:'junior:'+id,subjectId:id,kind:'junior',title:'Junior development',created:s.currentDate,deadline:plusDays(s.currentDate,28),defaultText:'Retain supported role',steps:[{date:s.currentDate,text:'Appointed'},{date:s.currentDate,text:'Milestone reached'}]}]});const b=seasonLifeAction(a,{type:'life-junior-review',id,choice:'specialist'});expect(lifeOf(b).staff[id].juniorResponsibility).toBe('specialist');expect(lifeOf(b).stories[0].resolved).toBe(s.currentDate);expect(b.coachContracts).toEqual(a.coachContracts);expect(b.player.cash).toBe(a.player.cash);expect(seasonLifeAction(b,{type:'life-junior-review',id,choice:'supported'})).toBe(b);});
 it('junior development needs an actual occupied slot and completed work',()=>{const s=career();const junior=s.coaches.find(c=>c.id.startsWith('junior-coach-'))!;const plan=s.trainingPlan.map(d=>({...d,competitionName:undefined,morning:buildTrainingCell('long-pot-routine'),afternoon:buildTrainingCell('rest'),evening:buildTrainingCell('rest')}));s.trainingCondition.injuryWeeks=0;s.coachContracts=[];expect(lifeOf(seasonLifeTraining(s,plan)).staff[junior.id]?.experience??0).toBe(0);s.coachContracts=[{...renewal().coachContracts[0],coachId:junior.id}];const a=seasonLifeTraining(s,plan);expect(lifeOf(a).staff[junior.id].experience).toBe(1);expect(lifeOf(seasonLifeTraining(a,plan)).staff[junior.id].experience).toBe(1);});
});
describe('doubles live engine and team settlement',()=>{
 it('attributes a modelled opponent foul to the correct doubles striker and preserves the penalty on replay',()=>{const {s,e}=pairs();const live=createTeamLiveMatch(s,e,0,2);live.teamContext={...live.teamContext!,turn:1};vi.spyOn(Math,'random').mockReturnValueOnce(.999).mockReturnValue(0);const next=advanceLiveVisit(live,'Pot Attempt','manual');expect(next.visitHistory[0].foulOccurred).toBe(true);expect(next.teamContext!.members[2].fouls).toBe(1);expect(next.playerPoints).toBeGreaterThanOrEqual(4);expect(next.teamContext?.foulReplayTurn).toBe(1);const replay=replayTeamFoul(next);expect(replay.playerPoints).toBe(next.playerPoints);expect(replay.teamContext?.turn).toBe(1);});
 it('archives older team results without losing trophy or award records at rollover',()=>{const {s,e}=pairs();s.careerDepth!.seasonLife!.teams=Array.from({length:82},(_,i)=>({...e,id:'old-team-'+i,status:'completed',champion:e.teams[0].name,award:250}));const next=reconcileSeasonLife({...s,season:'2030/31',currentDate:plusDays(s.currentDate,1)});expect(lifeOf(next).teams.filter(t=>t.id.startsWith('old-team-'))).toHaveLength(80);expect(lifeOf(next).archivedTeams).toHaveLength(2);expect(lifeOf(next).archivedTeams?.every(t=>t.won&&t.award===250)).toBe(true);expect(reconcileSeasonLife(next)).toBe(next);});
 it('retains team context through the actual save repair pipeline',()=>{const {s,e}=pairs();s.liveMatch=createTeamLiveMatch(s,e,0,2);const fixed=repairGameState(s);expect(fixed.liveMatch?.teamContext).toEqual(s.liveMatch.teamContext);});
 it('foul replay returns the offender without moving their partner into turn',()=>{const {s,e}=pairs(),live=createTeamLiveMatch(s,e,0,2);live.teamContext={...live.teamContext!,turn:2,foulReplayTurn:1};const next=replayTeamFoul(live);expect(next.teamContext?.turn).toBe(1);expect(next.teamContext?.order).toEqual([0,2,1,3]);expect(next.teamContext?.foulReplayTurn).toBeUndefined();expect(next.playerPoints).toBe(live.playerPoints);});
 it('keeps fixed four-player order, retains breaks, changes visits, alternates frame starters',()=>{random(32);const {s,e}=pairs();let live=createTeamLiveMatch(s,e,0,2);expect(live.teamContext?.order).toEqual([0,2,1,3]);let retained=0,switched=0;for(let n=0;n<250&&live.status==='In Progress';n++){const before=live;live=advanceLiveVisit(live,undefined,'manual','shot');if(live.frameHistory.length>before.frameHistory.length){expect(live.teamContext?.turn).toBe(live.frameStarterName===live.playerName?0:1);continue;}const log=live.visitHistory[0];if(log?.id===before.visitHistory[0]?.id)continue;expect(log?.participantId).toBe(before.teamContext!.members[before.teamContext!.order[before.teamContext!.turn]].id);if(log.retainedTable){retained++;expect(live.teamContext?.turn).toBe(before.teamContext?.turn);}else{switched++;expect(live.teamContext?.turn).toBe((before.teamContext!.turn+1)%4);}}expect(retained).toBeGreaterThan(0);expect(switched).toBeGreaterThan(0);});
 it('reloads an interrupted doubles match without changing the next outcome',()=>{random(77);const {s,e}=pairs();let live=createTeamLiveMatch(s,e,0,2);for(let i=0;i<12;i++)live=advanceLiveVisit(live);const saved=JSON.parse(JSON.stringify(live));vi.restoreAllMocks();random(88);const a=finish(live);vi.restoreAllMocks();random(88);const b=finish(saved);expect([b.playerFrames,b.opponentFrames]).toEqual([a.playerFrames,a.opponentFrames]);expect(b.teamContext).toEqual(a.teamContext);});
 it('simulation and playable neutral resolution use the same engine',()=>{const {s,e}=pairs();random(55);const a=simulateTeamRubber(s,e,0,2);vi.restoreAllMocks();random(55);const b=finish(createTeamLiveMatch(s,e,0,2));expect(a.score).toEqual([b.playerFrames,b.opponentFrames]);expect(a.individuals).toEqual(b.teamContext?.members);});
 it('singles only charge the two participants, not their partners',()=>{random();const {s,e}=pairs(),live=createTeamLiveMatch(s,e,0,0),done=finish(live);expect(done.teamContext!.members[1]).toEqual(live.teamContext!.members[1]);expect(done.teamContext!.members[3]).toEqual(live.teamContext!.members[3]);});
 it('simulates the teammate singles and advances ties without changing singles ledgers',()=>{random();let {s,e}=pairs();const before={matches:s.matches,rankings:s.competitionTables,history:s.history};s.currentDate=e.start;let live=finish(createTeamLiveMatch(s,e,0,0));s=finalizeLiveMatch(s,live);expect(lifeOf(s).teams[0].ties[0].results.length).toBe(2);expect(s.matches).toEqual(before.matches);expect(s.history).toEqual(before.history);expect(s.competitionTables).toEqual(before.rankings);expect(settleTeamMatch(s,live)).toBe(s);e=lifeOf(s).teams[0];if(e.ties[0].winner===undefined){live=finish(createTeamLiveMatch(s,e,0,2));s=settleTeamMatch(s,live);}e=lifeOf(s).teams[0];if(e.status==='accepted'){s.currentDate=e.end;live=finish(createTeamLiveMatch(s,e,2,0));s=settleTeamMatch(s,live);e=lifeOf(s).teams[0];if(e.ties[2].winner===undefined)s=settleTeamMatch(s,finish(createTeamLiveMatch(s,e,2,2)));}expect(lifeOf(s).teams[0].status).toBe('completed');expect(lifeOf(s).teams[0].champion).toBeTruthy();expect(Object.values(lifeOf(s).teams[0].playerAwards??{}).filter(n=>n===e.winnerShare)).toHaveLength(2);expect(Object.values(lifeOf(s).teams[0].playerAwards??{}).filter(n=>n===e.runnerUpShare)).toHaveLength(2);expect(s.finance.ledger.filter(x=>x.id==='team-fixture:award').length).toBeLessThanOrEqual(1);expect(s.matches).toEqual(before.matches);});
 it('refuses unavailable partners and conflicting bookings',()=>{const {s,e}=pairs();e.status='invited';s.careerSystems.pro.hasTourCard=false;s.player.age=18;s.worldPlayers.find(p=>p.id===e.partnerOptions[0].id)!.injuryWeeks=1;expect(teamChoice(s,e.id,'accept').lastAction).toMatch(/Partner/);s.careerDepth!.commitments.push({id:'clash',kind:'appearance',startDate:e.start,endDate:e.end,cost:0,income:0,fatigue:0,sharpness:0,status:'scheduled'});expect(teamConflict(s,e.start,e.end,e.id)).toContain('commitment');});
 it('protects amateur and Q Tour dates for young non-professional partners too',()=>{const {s,e}=pairs();const p=s.worldPlayers.find(p=>p.id===e.partnerOptions[0].id)!;p.age=19;p.hasTourCard=false;s.tournaments=[{...s.tournaments[0],type:'Amateur',startDate:e.start,endDate:e.end}];expect(availableTeamMember(s,p.id,e.start,e.end,'amateur')).toBe(false);});
 it('omits invitations when a valid field cannot be assembled',()=>{const s=career();s.worldPlayers=[];expect(lifeOf(offerTeam({...s,currentDate:plusDays(s.currentDate,1)})).teams).toEqual([]);});
 it('books each cost once, keeps equal award shares and enforces the two-event cap',()=>{const {s,e}=pairs();s.careerSystems.pro.hasTourCard=false;s.player.age=18;s.tournaments=s.tournaments.map(t=>({...t,startDate:plusDays(e.end,70),endDate:plusDays(e.end,71),status:'Available'}));s.careerDepth!.commitments=[];e.status='invited';delete e.accepted;const a=teamChoice(s,e.id,'accept');expect(lifeOf(a).teams[0].status).toBe('accepted');expect(a.player.cash).toBe(s.player.cash-25);expect(teamChoice(a,e.id,'accept').player.cash).toBe(a.player.cash);expect(a.finance.ledger.filter(x=>x.id.startsWith(e.id+':'))).toHaveLength(3);const b=putLife(s,{...lifeOf(s),teams:[{...e,id:'earlier-1',status:'completed',accepted:s.currentDate},{...e,id:'earlier-2',status:'withdrawn',accepted:s.currentDate},e]});expect(teamChoice(b,e.id,'accept').lastAction).toContain('season limit');});
 it('uses amateur pairs for a young Q Tour player and accepts completed singles as a free window',()=>{const {s,e}=pairs();s.careerSystems.pro.hasTourCard=false;s.player.age=19;s.player.careerStage='Q Tour';s.player.rankingLabel='Q Tour Ranking';s.currentDate=plusDays(s.currentDate,1);s.tournaments=s.tournaments.map(t=>({...t,startDate:plusDays(s.currentDate,200),endDate:plusDays(s.currentDate,201),status:'Available'}));s.careerDepth!.commitments=[];s.liveMatch={...createTeamLiveMatch(s,e,0,0),status:'Completed',teamContext:undefined};s.careerDepth!.seasonLife!.teams=[];const a=offerTeam(s);expect(lifeOf(a).teams[0]?.kind).toBe('amateur');});
 it('allows withdrawals without adding ranking points or trophies',()=>{const {s,e}=pairs();const a=teamChoice(s,e.id,'withdraw');expect(lifeOf(a).teams[0].status).toBe('withdrawn');expect(a.matches).toEqual(s.matches);expect(a.finance).toEqual(s.finance);});
});
describe('optional interviews and factual arcs',()=>{
 it('archives conclusions, keeps pending arcs, and suppresses archived duplicates',()=>{let s=career();const l=lifeOf(s);s=putLife(s,{...l,stories:Array.from({length:62},(_,i)=>({id:'conclusion-'+i,kind:'form',title:'Recovery '+i,created:s.currentDate,defaultText:'Patience',steps:[{date:s.currentDate,text:'Recovered'}],resolved:i===61?undefined:s.currentDate}))});const story={id:'new-form',kind:'form' as const,title:'Current concern',created:s.currentDate,defaultText:'Patience',steps:[]};const next=lifeStory(s,story);expect(lifeOf(next).stories.some(x=>x.id==='conclusion-61')).toBe(true);expect(lifeOf(next).archivedStories).toHaveLength(1);expect(lifeStory(next,s.careerDepth!.seasonLife!.stories[60])).toBe(next);});
 it('does not claim a coach reaction when preparing independently',()=>{const s=career();s.coachContracts=[];const a=offerInterview(s,{...initial.matches[0],round:'Final',tournamentClass:'Major'});const b=answerInterview(a,lifeOf(a).interviews[0].id,'candid');expect(lifeOf(b).interviews[0].reaction).toContain('independently');expect(lifeOf(b).interviews[0].reaction).not.toContain('trust increase');});
 it('triggers significant events once and applies a reply once',()=>{const s=career(),m={...initial.matches[0],id:'final',season:s.season,round:'Final',tournamentClass:'Major',result:'Won' as const,opponentId:s.worldPlayers[0].id};let a=offerInterview(s,m);expect(lifeOf(a).interviews).toHaveLength(1);expect(offerInterview(a,m)).toBe(a);const id=lifeOf(a).interviews[0].id;a=answerInterview(a,id,'challenge');expect(answerInterview(a,id,'praise')).toBe(a);expect(a.player.cash).toBe(s.player.cash);expect(a.sponsors).toEqual(s.sponsors);expect(lifeOf(a).interviews[0].context).toContain(m.opponentName);});
 it('allows a fresh interview for the same tournament in a later season',()=>{const s=career(),m={...initial.matches[0],round:'Final',tournamentClass:'Major',season:s.season};const a=offerInterview(s,m),b=offerInterview({...a,season:'2028/29'},{...m,season:'2028/29'});expect(lifeOf(b).interviews).toHaveLength(2);});
 it('expires after three days without punishment or a blocking story',()=>{const s=career(),a=offerInterview(s,{...initial.matches[0],round:'Final',tournamentClass:'Major'}),b=reconcileSeasonLife({...a,currentDate:plusDays(s.currentDate,4)});expect(lifeOf(b).interviews[0].response).toBe('private');expect(b.player.cash).toBe(a.player.cash);expect(depthOf(b).stories).toEqual(depthOf(a).stories);});
 it('does not fabricate a rival injury return',()=>{const s=career(),p=s.worldPlayers[0];s.careerDepth!.relationships[p.id]={opponentId:p.id,name:p.playerName,wins:2,losses:2,deciders:2,rivalry:true,recent:[],tactics:{}};const a=reconcileSeasonLife({...s,currentDate:plusDays(s.currentDate,1)});expect(lifeOf(a).stories.filter(x=>x.kind==='return')).toHaveLength(0);p.injuryWeeks=2;const b=reconcileSeasonLife({...a,currentDate:plusDays(s.currentDate,2)});b.worldPlayers.find(x=>x.id===p.id)!.injuryWeeks=0;const c=reconcileSeasonLife({...b,currentDate:plusDays(s.currentDate,20)});expect(lifeOf(c).stories.filter(x=>x.kind==='return')).toHaveLength(1);expect(reconcileSeasonLife(c)).toBe(c);});
});

describe('retired team eligibility',()=>{
 it('does not generate or accept new invitations for retired players',()=>{
  const {s,e}=pairs();s.careerSystems.lateCareer.retired=true;s.currentDate=plusDays(s.currentDate,1);e.status='invited';delete e.accepted;s.careerDepth!.seasonLife!.teams=[e];
  expect(offerTeam(s)).toBe(s);const refused=teamChoice(s,e.id,'accept');
  expect(refused.lastAction).toContain('retired');expect(refused.player.cash).toBe(s.player.cash);expect(lifeOf(refused).teams[0].status).toBe('invited');
 });
 it('rejects new rubbers in old retired entries while allowing withdrawal after a completed match',()=>{
  const {s,e}=pairs();s.currentDate=e.start;s.careerSystems.lateCareer.retired=true;
  expect(startTeamMatch(s,e.id).lastAction).toContain('retired');
  const live=createTeamLiveMatch(s,e,0,0);s.liveMatch={...live,status:'Completed'};
  const withdrawn=teamChoice(s,e.id,'withdraw');expect(lifeOf(withdrawn).teams[0].status).toBe('withdrawn');expect(withdrawn.finance).toEqual(s.finance);
 });
});
